// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shared_Class_Vivo_Apps.DB_Context_Vivo_MAIS;

#nullable disable

namespace Vivo_Apps_API.Migrations
{
    [DbContext(typeof(DemandasContext))]
    [Migration("20240308132013_DemandasContextMigration")]
    partial class DemandasContextMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Latin1_General_CI_AS")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shared_Class_Vivo_Apps.Data.ACESSOS_MOBILE", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CANAL")
                        .HasColumnType("int");

                    b.Property<int>("CARGO")
                        .HasColumnType("int");

                    b.Property<string>("CPF")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int?>("DDD")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DT_MOD")
                        .HasColumnType("datetime");

                    b.Property<bool?>("ELEGIVEL")
                        .HasColumnType("bit");

                    b.Property<string>("EMAIL")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("FIXA")
                        .HasColumnType("bit");

                    b.Property<int?>("LOGIN_MOD")
                        .HasColumnType("int");

                    b.Property<int?>("MATRICULA")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("NOME")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("OBS")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("PDV")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("REGIONAL")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("SENHA")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("STATUS")
                        .HasColumnType("bit");

                    b.Property<string>("TP_AFASTAMENTO")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("TP_STATUS")
                        .HasColumnType("int");

                    b.Property<string>("UF")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<byte[]>("UserAvatar")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("ID");

                    b.ToTable("ACESSOS_MOBILE", "dbo");
                });

            modelBuilder.Entity("Shared_Class_Vivo_Apps.Data.DEMANDA_ARQUIVOS_RESPOSTA", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<byte[]>("ARQUIVO")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("EXT_ARQUIVO")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("ID_RESPOSTA")
                        .HasColumnType("int");

                    b.Property<string>("NOME_CAMPO")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ID_RESPOSTA");

                    b.ToTable("DEMANDA_ARQUIVOS_RESPOSTA", "Demandas");
                });

            modelBuilder.Entity("Shared_Class_Vivo_Apps.Data.DEMANDA_CAMPOS_CHAMADO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CAMPO")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("ID_CHAMADO")
                        .HasColumnType("int");

                    b.Property<string>("VALOR")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ID_CHAMADO");

                    b.ToTable("DEMANDA_CAMPOS_CHAMADO", "Demandas");
                });

            modelBuilder.Entity("Shared_Class_Vivo_Apps.Data.DEMANDA_CAMPOS_FILA", b =>
                {
                    b.Property<int>("ID_CAMPOS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_CAMPOS"));

                    b.Property<string>("CAMPO")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<bool>("CAMPO_SUSPENSO")
                        .HasColumnType("bit");

                    b.Property<string>("DT_CRIACAO")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("ID_SUB_FILA")
                        .HasColumnType("int");

                    b.Property<string>("MASCARA")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("MAT_CRIADOR")
                        .HasColumnType("int");

                    b.Property<string>("REGIONAL")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<bool>("STATUS_CAMPOS_FILA")
                        .HasColumnType("bit");

                    b.HasKey("ID_CAMPOS");

                    b.HasIndex("ID_SUB_FILA");

                    b.ToTable("DEMANDA_CAMPOS_FILA", "dbo");
                });

            modelBuilder.Entity("Shared_Class_Vivo_Apps.Data.DEMANDA_CHAMADO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("DATA_ABERTURA")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DATA_FECHAMENTO")
                        .HasColumnType("datetime");

                    b.Property<int>("ID_FILA_CHAMADO")
                        .HasColumnType("int");

                    b.Property<int?>("MATRICULA_RESPONSAVEL")
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<int>("MATRICULA_SOLICITANTE")
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<string>("PRIORIDADE")
                        .HasMaxLength(550)
                        .IsUnicode(false)
                        .HasColumnType("varchar(550)");

                    b.Property<string>("REGIONAL")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("ID");

                    b.HasIndex("ID_FILA_CHAMADO");

                    b.HasIndex("MATRICULA_RESPONSAVEL");

                    b.HasIndex("MATRICULA_SOLICITANTE");

                    b.ToTable("DEMANDA_CHAMADO", "Demandas", t =>
                        {
                            t.HasTrigger("tr_Demandas_DEMANDA_CHAMADO_85b3748a-c03c-4495-b002-e1b60e5965c5_Sender");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Shared_Class_Vivo_Apps.Data.DEMANDA_CHAMADO_RESPOSTA", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DATA_RESPOSTA")
                        .HasColumnType("datetime");

                    b.Property<int>("ID_CHAMADO")
                        .HasColumnType("int");

                    b.Property<int>("MATRICULA_RESPONSAVEL")
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<string>("RESPOSTA")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ID_CHAMADO");

                    b.HasIndex("MATRICULA_RESPONSAVEL");

                    b.ToTable("DEMANDA_CHAMADO_RESPOSTA", "Demandas");
                });

            modelBuilder.Entity("Shared_Class_Vivo_Apps.Data.DEMANDA_HISTORICO_PRIORIDADE", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DATA")
                        .IsUnicode(false)
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_CHAMADO")
                        .HasColumnType("int");

                    b.Property<int>("MAT_RESPONSAVEL")
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<string>("PRIORIDADE")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ID_CHAMADO");

                    b.HasIndex("MAT_RESPONSAVEL");

                    b.ToTable("DEMANDA_HISTORICO_PRIORIDADE", "Demandas");
                });

            modelBuilder.Entity("Shared_Class_Vivo_Apps.Data.DEMANDA_RESPONSAVEL_FILA", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ID_SUB_FILA")
                        .HasColumnType("int");

                    b.Property<int?>("MATRICULA_RESPONSAVEL")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ID_SUB_FILA");

                    b.ToTable("DEMANDA_RESPONSAVEL_FILA", "dbo");
                });

            modelBuilder.Entity("Shared_Class_Vivo_Apps.Data.DEMANDA_STATUS_CHAMADO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DATA")
                        .HasColumnType("datetime");

                    b.Property<int>("ID_CHAMADO")
                        .HasColumnType("int");

                    b.Property<int>("ID_RESPOSTA")
                        .HasColumnType("int");

                    b.Property<int?>("MAT_DESTINARARIO")
                        .HasColumnType("int");

                    b.Property<int?>("MAT_DESTINATARIO")
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<int?>("MAT_QUEM_REDIRECIONOU")
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<string>("STATUS")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ID_CHAMADO");

                    b.HasIndex("ID_RESPOSTA")
                        .IsUnique();

                    b.HasIndex("MAT_DESTINARARIO");

                    b.HasIndex("MAT_QUEM_REDIRECIONOU");

                    b.ToTable("DEMANDA_STATUS_CHAMADO", "Demandas");
                });

            modelBuilder.Entity("Shared_Class_Vivo_Apps.Data.DEMANDA_SUB_FILA", b =>
                {
                    b.Property<int>("ID_SUB_FILA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_SUB_FILA"));

                    b.Property<bool>("CAMPOS_AUTO")
                        .HasColumnType("bit");

                    b.Property<bool>("CAMPOS_IDENT_USER")
                        .HasColumnType("bit");

                    b.Property<string>("DATA_CRIACAO")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("DESCRICAO")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int?>("ID_ANTIGO")
                        .HasColumnType("int");

                    b.Property<int>("ID_TIPO_FILA")
                        .HasColumnType("int");

                    b.Property<int?>("MAT_CRIADOR")
                        .HasColumnType("int");

                    b.Property<string>("NOME_SUB_FILA")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("REGIONAL")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("SLA")
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<bool>("STATUS_SUB_FILA")
                        .HasColumnType("bit");

                    b.HasKey("ID_SUB_FILA");

                    b.HasIndex("ID_TIPO_FILA");

                    b.ToTable("DEMANDA_SUB_FILA", "dbo");
                });

            modelBuilder.Entity("Shared_Class_Vivo_Apps.Data.DEMANDA_TIPO_FILA", b =>
                {
                    b.Property<int>("ID_TIPO_FILA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_TIPO_FILA"));

                    b.Property<string>("DESCRICAO")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("DT_CRIACAO")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("MAT_CRIADOR")
                        .HasColumnType("int");

                    b.Property<string>("NOME_TIPO_FILA")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("REGIONAL")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<bool>("STATUS_TIPO_FILA")
                        .HasColumnType("bit");

                    b.HasKey("ID_TIPO_FILA");

                    b.ToTable("DEMANDA_TIPO_FILA", "dbo");
                });

            modelBuilder.Entity("Shared_Class_Vivo_Apps.Data.DEMANDA_VALORES_CAMPOS_SUSPENSO", b =>
                {
                    b.Property<int>("ID_VALORES")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_VALORES"));

                    b.Property<int>("ID_CAMPOS")
                        .HasColumnType("int");

                    b.Property<bool>("STATUS")
                        .HasColumnType("bit");

                    b.Property<string>("VALOR")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("ID_VALORES");

                    b.HasIndex("ID_CAMPOS");

                    b.ToTable("DEMANDA_VALORES_CAMPOS_SUSPENSO", "dbo");
                });

            modelBuilder.Entity("Shared_Class_Vivo_Apps.Data.DEMANDA_ARQUIVOS_RESPOSTA", b =>
                {
                    b.HasOne("Shared_Class_Vivo_Apps.Data.DEMANDA_CHAMADO_RESPOSTA", "RESPOSTANav")
                        .WithMany("ARQUIVOS")
                        .HasForeignKey("ID_RESPOSTA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RESPOSTANav");
                });

            modelBuilder.Entity("Shared_Class_Vivo_Apps.Data.DEMANDA_CAMPOS_CHAMADO", b =>
                {
                    b.HasOne("Shared_Class_Vivo_Apps.Data.DEMANDA_CHAMADO", "DEMANDANav")
                        .WithMany("Campos")
                        .HasForeignKey("ID_CHAMADO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DEMANDANav");
                });

            modelBuilder.Entity("Shared_Class_Vivo_Apps.Data.DEMANDA_CAMPOS_FILA", b =>
                {
                    b.HasOne("Shared_Class_Vivo_Apps.Data.DEMANDA_SUB_FILA", "ID_SUB_FILANavigation")
                        .WithMany("DEMANDA_CAMPOS_FILAs")
                        .HasForeignKey("ID_SUB_FILA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ID_SUB_FILANavigation");
                });

            modelBuilder.Entity("Shared_Class_Vivo_Apps.Data.DEMANDA_CHAMADO", b =>
                {
                    b.HasOne("Shared_Class_Vivo_Apps.Data.DEMANDA_SUB_FILA", "Fila")
                        .WithMany("DEMANDAS")
                        .HasForeignKey("ID_FILA_CHAMADO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared_Class_Vivo_Apps.Data.ACESSOS_MOBILE", "Responsavel")
                        .WithMany("DemandasResponsavel")
                        .HasForeignKey("MATRICULA_RESPONSAVEL")
                        .HasPrincipalKey("MATRICULA");

                    b.HasOne("Shared_Class_Vivo_Apps.Data.ACESSOS_MOBILE", "Solicitante")
                        .WithMany("DemandasSolicitadas")
                        .HasForeignKey("MATRICULA_SOLICITANTE")
                        .HasPrincipalKey("MATRICULA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fila");

                    b.Navigation("Responsavel");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("Shared_Class_Vivo_Apps.Data.DEMANDA_CHAMADO_RESPOSTA", b =>
                {
                    b.HasOne("Shared_Class_Vivo_Apps.Data.DEMANDA_CHAMADO", "DEMANDANav")
                        .WithMany("Respostas")
                        .HasForeignKey("ID_CHAMADO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared_Class_Vivo_Apps.Data.ACESSOS_MOBILE", "Responsavel")
                        .WithMany()
                        .HasForeignKey("MATRICULA_RESPONSAVEL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DEMANDANav");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("Shared_Class_Vivo_Apps.Data.DEMANDA_HISTORICO_PRIORIDADE", b =>
                {
                    b.HasOne("Shared_Class_Vivo_Apps.Data.DEMANDA_CHAMADO", "DEMANDANav")
                        .WithMany("Historico_Prioridade")
                        .HasForeignKey("ID_CHAMADO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared_Class_Vivo_Apps.Data.ACESSOS_MOBILE", "Responsavel")
                        .WithMany()
                        .HasForeignKey("MAT_RESPONSAVEL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DEMANDANav");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("Shared_Class_Vivo_Apps.Data.DEMANDA_RESPONSAVEL_FILA", b =>
                {
                    b.HasOne("Shared_Class_Vivo_Apps.Data.DEMANDA_SUB_FILA", "ID_SUB_FILANavigation")
                        .WithMany("DEMANDA_RESPONSAVEL_FILAs")
                        .HasForeignKey("ID_SUB_FILA");

                    b.Navigation("ID_SUB_FILANavigation");
                });

            modelBuilder.Entity("Shared_Class_Vivo_Apps.Data.DEMANDA_STATUS_CHAMADO", b =>
                {
                    b.HasOne("Shared_Class_Vivo_Apps.Data.DEMANDA_CHAMADO", "DEMANDANav")
                        .WithMany("Status")
                        .HasForeignKey("ID_CHAMADO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared_Class_Vivo_Apps.Data.DEMANDA_CHAMADO_RESPOSTA", "Resposta")
                        .WithOne("Status")
                        .HasForeignKey("Shared_Class_Vivo_Apps.Data.DEMANDA_STATUS_CHAMADO", "ID_RESPOSTA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared_Class_Vivo_Apps.Data.ACESSOS_MOBILE", "Para_Quem_redirecionou")
                        .WithMany()
                        .HasForeignKey("MAT_DESTINARARIO");

                    b.HasOne("Shared_Class_Vivo_Apps.Data.ACESSOS_MOBILE", "Quem_redirecionou")
                        .WithMany()
                        .HasForeignKey("MAT_QUEM_REDIRECIONOU");

                    b.Navigation("DEMANDANav");

                    b.Navigation("Para_Quem_redirecionou");

                    b.Navigation("Quem_redirecionou");

                    b.Navigation("Resposta");
                });

            modelBuilder.Entity("Shared_Class_Vivo_Apps.Data.DEMANDA_SUB_FILA", b =>
                {
                    b.HasOne("Shared_Class_Vivo_Apps.Data.DEMANDA_TIPO_FILA", "ID_TIPO_FILANavigation")
                        .WithMany("DEMANDA_SUB_FILAs")
                        .HasForeignKey("ID_TIPO_FILA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ID_TIPO_FILANavigation");
                });

            modelBuilder.Entity("Shared_Class_Vivo_Apps.Data.DEMANDA_VALORES_CAMPOS_SUSPENSO", b =>
                {
                    b.HasOne("Shared_Class_Vivo_Apps.Data.DEMANDA_CAMPOS_FILA", "ID_CAMPOSNavigation")
                        .WithMany("DEMANDA_VALORES_CAMPOS_SUSPENSOs")
                        .HasForeignKey("ID_CAMPOS")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ID_CAMPOSNavigation");
                });

            modelBuilder.Entity("Shared_Class_Vivo_Apps.Data.ACESSOS_MOBILE", b =>
                {
                    b.Navigation("DemandasResponsavel");

                    b.Navigation("DemandasSolicitadas");
                });

            modelBuilder.Entity("Shared_Class_Vivo_Apps.Data.DEMANDA_CAMPOS_FILA", b =>
                {
                    b.Navigation("DEMANDA_VALORES_CAMPOS_SUSPENSOs");
                });

            modelBuilder.Entity("Shared_Class_Vivo_Apps.Data.DEMANDA_CHAMADO", b =>
                {
                    b.Navigation("Campos");

                    b.Navigation("Historico_Prioridade");

                    b.Navigation("Respostas");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Shared_Class_Vivo_Apps.Data.DEMANDA_CHAMADO_RESPOSTA", b =>
                {
                    b.Navigation("ARQUIVOS");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Shared_Class_Vivo_Apps.Data.DEMANDA_SUB_FILA", b =>
                {
                    b.Navigation("DEMANDAS");

                    b.Navigation("DEMANDA_CAMPOS_FILAs");

                    b.Navigation("DEMANDA_RESPONSAVEL_FILAs");
                });

            modelBuilder.Entity("Shared_Class_Vivo_Apps.Data.DEMANDA_TIPO_FILA", b =>
                {
                    b.Navigation("DEMANDA_SUB_FILAs");
                });
#pragma warning restore 612, 618
        }
    }
}
