
--select * from ACESSOS_MOBILE where MATRICULA IN (
--select DISTINCT(MATRICULA_SOLICITANTE) from [Vivo_MAIS].Demandas.DEMANDA_RELACAO_CHAMADO )

select TOP 1 * from ACESSO where Login = '151191'
select top 100 * from ACESSO_PERMISSAO_MENU
--	Insert into ACESSO VALUES('165088','João Matheus de Brito Almeida','Joao.malmeida@telefonica.com','NE',null,null,'ATIVO',0)
--Insert into ACESSO_PERMISSAO_MENU VALUES ((SELECT IdAcesso from ACESSO WHERE Login = '165088'), 'SUPORTE','ADMINISTRATIVO')
select * from CONTROLE_DE_DEMANDAS_FILA
select * from CONTROLE_DE_DEMANDAS_CAMPOS_FILA where ID_FILA IN (573,574)

    --B.CAMPO,
    --B.VALOR
    --E.RESPOSTA

    select COUNT(*) from CONTROLE_DE_DEMANDAS_CHAMADO where ID_FILA_CHAMADO in (573,574)


    SELECT A.ID,
    F.FILA,
    C.STATUS,
    D.Nome,
    A.DATA_ABERTURA,
    E.DATA_RESPOSTA,
    MAX(CASE WHEN B.CAMPO = 'ADABAS' THEN B.VALOR END) AS ADABAS,
    MAX(CASE WHEN B.CAMPO = 'CPF Do Cliente' THEN B.VALOR END) AS CPF_Do_Cliente,
    MAX(CASE WHEN B.CAMPO = 'Nome Do Cliente' THEN B.VALOR END) AS Nome_Do_Cliente
FROM CONTROLE_DE_DEMANDAS_CHAMADO A

inner JOIN (SELECT * FROM CONTROLE_DE_DEMANDAS_RELACAO_CAMPOS_CHAMADO B WHERE B.CAMPO IN ('ADABAS'
, 'Nome Do Cliente','CPF Do Cliente'
)) B ON A.ID_CAMPOS_CHAMADO = B.ID_CAMPOS_CHAMADO

LEFT JOIN (
    SELECT ID,ID_STATUS_CHAMADO,STATUS,ROW_NUMBER() OVER (PARTITION BY ID_STATUS_CHAMADO ORDER BY ID desc) AS rn
    FROM CONTROLE_DE_DEMANDAS_RELACAO_STATUS_CHAMADO
) C ON A.ID_STATUS_CHAMADO = C.ID_STATUS_CHAMADO AND C.rn = 1

LEFT JOIN ACESSO D ON A.MATRICULA_SOLICITANTE = D.Login

left JOIN (
    SELECT ID,ID_CHAMADO,DATA_RESPOSTA,ROW_NUMBER() OVER (PARTITION BY ID_CHAMADO ORDER BY ID desc) AS rn
    FROM CONTROLE_DE_DEMANDAS_CHAMADO_RESPOSTA
) E ON A.ID = E.ID_CHAMADO AND E.rn = 1

LEFT JOIN CONTROLE_DE_DEMANDAS_FILA F ON A.ID_FILA_CHAMADO = F.ID
WHERE A.ID_FILA_CHAMADO IN (573, 574)
GROUP BY A.ID, F.FILA, C.STATUS, D.Nome, A.DATA_ABERTURA, E.DATA_RESPOSTA;



select TOP 10 * from CONTROLE_DE_DEMANDAS_CHAMADO_RESPOSTA

    SELECT ID,ID_CHAMADO,DATA_RESPOSTA,ROW_NUMBER() OVER (PARTITION BY ID_CHAMADO ORDER BY ID desc) AS rn
    FROM CONTROLE_DE_DEMANDAS_CHAMADO_RESPOSTA

Status
Solicitante
Data Abertura
Data Ult. Alteração 
ADABAS
Nome Da Loja
Login
--delete ACESSOS_MOBILE_PENDENTE WHERE MATRICULA = 165088
--delete PERFIL_USUARIO_PENDENTE where ID_ACESSO_PENDENTE = 5221
--delete HISTORICO_ACESSOS_MOBILE_PENDENTE where ID_ACESSOS_PENDENTE = 5221

--select * from CONTROLE_DE_DEMANDAS_OPERADORES
--insert into  PERFIL_USUARIO
--values (165088,1,'2024-06-28 00:00:00.000', 151191 )

--insert into 
--CONTROLE_DE_DEMANDAS_OPERADORES
--values ('165088','João Matheus De Brito Almeida','Analista','NE') 

--select top 1 * fROM ACESSOS_MOBILE order by id desc

--insert into ACESSOS_MOBILE 
--values
--(
--'joao.malmeida@telefonica.com'
--,'165088'
--,'80039AE51A10925FDF69FD2BA996315B'
--,'NE'
--,4
--,1	
--,'NERECIFE01'
--,'000.000.000-00'
--,'João Matheus De Brito Almeida'
--,'PE'
--,1
--,1	
--,NULL	
--,'OK'
--,NULL	
--,151191	
--,'2024-06-28 12:40:55.163'
--,NULL	
--,81	
--,NULL
--)

--select * from CONTROLE_DE_DEMANDAS_FILA where fila like '%fixa%' and REGIONAL = 'MG'
--select * from Cardapio.PRODUTOS_CARDAPIO_FICHA_TECNICA
--select * from Cardapio.PRODUTOS_CARDAPIO_IMAGENS

--select * from Demandas.DEMANDA_RELACAO_TREINAMENTO_FINALIZADO	
--insert into CONTROLE_DE_DEMANDAS_FILA
--values
--('DELIBERAÇÃO COMERCIAL B2B',
--'Não',
--'151191',
--'Não',
--'FIXA - COMERCIAL/QUALIDADE',
--'MG',
--'Não')

