// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.DataGRC
{
    public partial class AG_CREDENCIADOS_HISTORICA
    {
        public string COD_CREDENC { get; set; }
        public decimal? COD_ENT_VEND { get; set; }
        public decimal? COD_ALVO { get; set; }
        public string OBS { get; set; }
        public string NOME_ENT { get; set; }
        public decimal? NUM_CGC { get; set; }
        public string NOME_ENT_ABR { get; set; }
        public string NUM_INSCR_EST { get; set; }
        public DateTime? DAT_INI_ENT { get; set; }
        public DateTime? DAT_FIM_ENT { get; set; }
        public decimal? COD_CLI_SAP { get; set; }
        public decimal? COD_CREDOR { get; set; }
        public string DOM_FISCAL { get; set; }
        public string TIP_LOGRAD { get; set; }
        public string NOME_LOGRAD { get; set; }
        public string NUM_LOGRAD { get; set; }
        public string COMPL_LOGRAD { get; set; }
        public string CEP_LOGRAD { get; set; }
        public string NOME_BAIRRO { get; set; }
        public string NOME_LOCAL { get; set; }
        public string DES_REG { get; set; }
        public string NOM_CASC { get; set; }
        public decimal? COD_GESTOR { get; set; }
        public string NOME_GESTOR { get; set; }
        public string COD_SIT_CML { get; set; }
        public DateTime? DAT_INI { get; set; }
        public string DES_SIT_CML { get; set; }
        public string DES_SEC { get; set; }
        public string DES_GEN_ENT { get; set; }
        public string DES_ACTIV { get; set; }
        public string DES_REG_1 { get; set; }
        public string ESCV { get; set; }
        public string CNTR_DSTR { get; set; }
        public string DT_CADASTRO { get; set; }
    }
}