// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.DataGRC
{
    public partial class ATV_HISTORICO_IMEI
    {
        public string SAP_CPF_CNPJ { get; set; }
        public int? QTD { get; set; }
    }
}