// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vivo_Apps_API.DataGRC
{
    public partial class CADASTRO_PDV
    {
        public string Vendedor { get; set; }
        public string Cnpj { get; set; }
        public DateTime? DataInicioContrato { get; set; }
        public DateTime? DataFimContrato { get; set; }
        public string RazaoSocial { get; set; }
        public string NomeFantasia { get; set; }
        public string InscricaoEstadual { get; set; }
        public string OptanteSimples { get; set; }
        public string Regional { get; set; }
        public string Cep { get; set; }
        public string Endereco { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Numero { get; set; }
        public string Complemento { get; set; }
        public string Contato { get; set; }
        public string Ddd { get; set; }
        public string Telefone { get; set; }
        public string Celular { get; set; }
        public string EmailFinanceiro { get; set; }
        public string EmailComercial { get; set; }
        public string EmailDivulgação { get; set; }
        public string CodigoBanco { get; set; }
        public string Banco { get; set; }
        public string Agencia { get; set; }
        public string NumeroConta { get; set; }
        public string DigitoVerificador { get; set; }
        public string SetorAtividade { get; set; }
        public string Uf { get; set; }
        public string PontoVenda { get; set; }
        public string Genero { get; set; }
        public string Canal { get; set; }
        public string StatusCallidus { get; set; }
        public string Instancia { get; set; }
        public string Atividade { get; set; }
        public string AtualEstrelagem { get; set; }
        public string CodigoCliente { get; set; }
        public string CodigoFornecedor { get; set; }
        public string CodIbge { get; set; }
        public string Ixos { get; set; }
        public string COD_REDE_VENDEDOR { get; set; }
        public string AREA { get; set; }
        public string LoginSiebel { get; set; }
        public string AreaAtuacaoPDV { get; set; }
        public DateTime? Data_Credenciamento { get; set; }
        public DateTime? Data_Descredenciamento { get; set; }
        public string TIPO_MINUTA { get; set; }
        public string MODELO_CONTRATO { get; set; }
        public string DRN { get; set; }
        public string DATA_ENVIO { get; set; }
        public string DATA_RECEBIMENTO { get; set; }
        public string VIGENCIA_INICIO { get; set; }
        public string VIGENCIA_FIM { get; set; }
        public string DMS { get; set; }
        public string ADMINISTRACAO { get; set; }
        public string ASSINATURA_NO_CONTRATO_VIVO { get; set; }
        public string SOCIO1 { get; set; }
        public string CPF { get; set; }
        public string SOCIO2 { get; set; }
        public string CPF2 { get; set; }
        public string SOCIO3 { get; set; }
        public string CPF3 { get; set; }
        public string SOCIO4 { get; set; }
        public string CPF4 { get; set; }
        public string VIGENCIA_ATUAL { get; set; }
        public string RENOVAÇÃO_AUTOMATICA { get; set; }
        public string Modelo_Loja { get; set; }
        public string Tipo_Loja { get; set; }
        public string Local_Loja { get; set; }
        public string GSS { get; set; }
        public string Clusters { get; set; }
        public string Estrelagem { get; set; }
    }
}