// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.DataGRC
{
    public partial class CADASTRO_ASSOCIACAO_FDV_DEZEMBRO
    {
        public string VENDEDOR { get; set; }
        public string MATRICULA_GC { get; set; }
        public DateTime? DATA_CADASTRO_GC { get; set; }
        public string MATRICULA_GC_ANT { get; set; }
        public DateTime? DATA_CADASTRO_GC_ANT { get; set; }
        public string MATRICULA_SELLIN { get; set; }
        public DateTime? DATA_CADASTRO_SELLIN { get; set; }
        public string MATRICULA_SELLIN_ANT { get; set; }
        public DateTime? DATA_CADASTRO_SELLIN_ANT { get; set; }
        public string MATRICULA_TERRITORIAL { get; set; }
        public DateTime? DATA_CADASTRO_TERRITORIAL { get; set; }
        public string MATRICULA_TERRITORIAL_ANT { get; set; }
        public DateTime? DATA_CADASTRO_TERRITORIAL_ANT { get; set; }
        public string MATRICULA_ALTERACAO { get; set; }
        public DateTime? DATA { get; set; }
    }
}