// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vivo_Apps_API.DataGRC
{
    public partial class CADASTRO_GERENTE_CONTA
    {
        public int ID { get; set; }
        public string Matricula { get; set; }
        public string Nome { get; set; }
        public string UF { get; set; }
        public string CPF { get; set; }
        public string Email { get; set; }
        public string Tipo { get; set; }
        public string Situacao { get; set; }
        public string Ddd { get; set; }
        public string Cargo { get; set; }
        public string Origem { get; set; }
        public string SellIn { get; set; }
        public DateTime? DataCadastro { get; set; }
    }
}