// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.DataGRC
{
    public partial class CADASTRO_X_VIVO_SIM
    {
        public int ID { get; set; }
        public string LOGIN { get; set; }
        public string UF { get; set; }
        public string DDD { get; set; }
    }
}