// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vivo_Apps_API.DataGRC
{
    public partial class CADASTRO_NOME_REDE
    {
        public int ID { get; set; }
        public string COD_REDE_VENDEDOR { get; set; }
        public string AREA { get; set; }
        public string REDE { get; set; }
        public string CANAL { get; set; }
        public string GENERO { get; set; }
        public string DT_CRIACAO { get; set; }
        public string LOGIN_CRIACAO { get; set; }
    }
}