// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vivo_Apps_API.DataGRC
{
    public partial class CADASTRO_X_VIVO_SIM_X_CANAL
    {
        public int ID { get; set; }
        public string LOGIN { get; set; }
        public string CANAL { get; set; }
    }
}