// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vivo_Apps_API.DataGRC
{
    public partial class CADASTRO_PDV_COMPLEMENTO_AUX
    {
        public string ADABAS { get; set; }
        public string TIPO_MINUTA { get; set; }
        public string MODELO_CONTRATO { get; set; }
        public string DRN { get; set; }
        public string DATA_ENVIO { get; set; }
        public string DATA_RECEBIMENTO { get; set; }
        public string VIGENCIA_INICIO { get; set; }
        public string VIGENCIA_FIM { get; set; }
        public string VIGENCIA_ATUAL { get; set; }
        public string RENOVAÇÃO_AUTOMATICA { get; set; }
        public string DMS { get; set; }
        public string ADMINISTRACAO { get; set; }
        public string ASSINATURA_NO_CONTRATO_VIVO { get; set; }
        public string SOCIO1 { get; set; }
        public string CPF { get; set; }
        public string SOCIO2 { get; set; }
        public string CPF2 { get; set; }
        public string SOCIO3 { get; set; }
        public string CPF3 { get; set; }
        public string SOCIO4 { get; set; }
        public string CPF4 { get; set; }
    }
}