// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vivo_Apps_API.DataGRC
{
    public partial class CNS_HIERARQUIA_CAMPANHA
    {
        public string DATA { get; set; }
        public string VENDEDOR { get; set; }
        public string REDE { get; set; }
        public string ID_SIEBEL { get; set; }
        public string NOME_FANTASIA { get; set; }
        public string Uf { get; set; }
        public string DDD { get; set; }
        public string TERRITORIO { get; set; }
        public string REGIONAL { get; set; }
        public string CANAL { get; set; }
        public string DIRETOR { get; set; }
        public string MATRICULA_DIRETOR { get; set; }
        public string NM_GERENTE_DIVISAO_TRTL { get; set; }
        public string RE_GERENTE_DIVISAO_TRTL { get; set; }
        public string CLS_GERENTE_DIVISAO { get; set; }
        public string NM_GERENTE_SECAO_TRTL { get; set; }
        public string RE_GERENTE_SECAO_TRTL { get; set; }
        public string CLS_GERENTE_SECAO_TRTL { get; set; }
        public string NM_GERENTE_CONTAS_SELL_IN { get; set; }
        public string RE_GERENTE_CONTAS_SELL_IN { get; set; }
        public string CLS_GERENTE_CONTAS_SELL_IN { get; set; }
        public string NM_GERENTE_CONTAS_SELL_OUT { get; set; }
        public string RE_GERENTE_CONTAS_SELL_OUT { get; set; }
        public string CLS_GERENTE_CONTAS_SELL_OUT { get; set; }
        public string NM_GERENTE_KAM_REGIONAL { get; set; }
        public string RE_GERENTE_KAM_REGIONAL { get; set; }
        public string NM_GERENTE_KAM_NACIONAL { get; set; }
        public string RE_GERENTE_KAM_NACIONAL { get; set; }
        public string NM_GERENTE_SECAO_CANAL { get; set; }
        public string RE_GERENTE_SECAO_CANAL { get; set; }
    }
}