// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vivo_Apps_API.DataGRC
{
    public partial class CNS_VIVO_ADIANTE
    {
        public string UNIDADE_REGIONAL { get; set; }
        public string TERRITORIO { get; set; }
        public string NOMETERRITORIO { get; set; }
        public string TERRITORIORE { get; set; }
        public string SECAO { get; set; }
        public string NOMESECAO { get; set; }
        public string SECAO_RE { get; set; }
        public string G_CONTAS_RE { get; set; }
        public string G_CONTAS { get; set; }
        public string DDD { get; set; }
        public string VENDEDOR { get; set; }
        public string NomeFantasia { get; set; }
        public string GENEROVENDEDOR { get; set; }
        public string LOGRADOURO { get; set; }
        public decimal? NUMERO { get; set; }
        public string COMPLEMENTO { get; set; }
        public string BAIRRO { get; set; }
        public string CIDADE { get; set; }
        public string CEP { get; set; }
        public string UFLOGRADOURO { get; set; }
        public string LATITUDE { get; set; }
        public string LONGITUDE { get; set; }
    }
}