// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vivo_Apps_API.DataGRC
{
    public partial class CNS_CADASTRO_GERAL_PDV
    {
        public string Vendedor { get; set; }
        public string Cnpj { get; set; }
        public DateTime? DataInicioContrato { get; set; }
        public DateTime? DataFimContrato { get; set; }
        public string RazaoSocial { get; set; }
        public string NomeFantasia { get; set; }
        public string InscricaoEstadual { get; set; }
        public string OptanteSimples { get; set; }
        public string Regional { get; set; }
        public string Cep { get; set; }
        public string Endereco { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Numero { get; set; }
        public string Complemento { get; set; }
        public string Contato { get; set; }
        public string Ddd { get; set; }
        public string Telefone { get; set; }
        public string Celular { get; set; }
        public string EmailFinanceiro { get; set; }
        public string EmailComercial { get; set; }
        public string EmailDivulgação { get; set; }
        public string CodigoBanco { get; set; }
        public string Banco { get; set; }
        public string Agencia { get; set; }
        public string NumeroConta { get; set; }
        public string DigitoVerificador { get; set; }
        public string SetorAtividade { get; set; }
        public string Uf { get; set; }
        public string PontoVenda { get; set; }
        public string Genero { get; set; }
        public string Canal { get; set; }
        public string StatusCallidus { get; set; }
        public string Instancia { get; set; }
        public string Atividade { get; set; }
        public string AtualEstrelagem { get; set; }
        public string CodigoCliente { get; set; }
        public string CodigoFornecedor { get; set; }
        public string CodIbge { get; set; }
        public string Ixos { get; set; }
        public string REDE { get; set; }
        public string TERRITORIO { get; set; }
        public string MATRICULA_TERRITORIO { get; set; }
        public string SELL_IN { get; set; }
        public string MATRICULA_SELLIN { get; set; }
        public string GERENTE_CONTAS { get; set; }
        public string MATRICULA_GERENTE_CONTAS { get; set; }
        public string LoginSiebel { get; set; }
        public string AREA { get; set; }
        public string AreaAtuacaoPDV { get; set; }
        public string Origem { get; set; }
        public DateTime? Data_Credenciamento { get; set; }
        public DateTime? Data_Descredenciamento { get; set; }
        public string Modelo_Loja { get; set; }
        public string Tipo_Loja { get; set; }
        public string Local_Loja { get; set; }
        public string GSS { get; set; }
        public string Clusters { get; set; }
        public string Estrelagem { get; set; }
        public string EMAIL_GC { get; set; }
        public string EMAIL_SELL_IN { get; set; }
        public string GERENTE_DIVISAO { get; set; }
        public string REGIAO { get; set; }
    }
}