// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.DataGRC
{
    public partial class CNS_GERENTE_TERRITORIO_ATIVO
    {
        public int ID { get; set; }
        public string DDD { get; set; }
        public string MATRICULA { get; set; }
        public string NOME { get; set; }
        public string AREA_ATUACAO_DDD { get; set; }
        public DateTime? DATA_EFETIVA_GESTAO { get; set; }
        public DateTime? DATA_CADASTRO { get; set; }
        public string STATUS { get; set; }
    }
}