// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.DataGRC
{
    public partial class DE_PARA_DDD_NACIONAL
    {
        public string Vendedor { get; set; }
        public string Cnpj { get; set; }
        public DateTime DataInicioContrato { get; set; }
        public DateTime DataFimContrato { get; set; }
        public string RazaoSocial { get; set; }
        public string NomeFantasia { get; set; }
        public string Regional { get; set; }
        public string Territorial { get; set; }
        public string Cep { get; set; }
        public string Endereco { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Numero { get; set; }
        public string Complemento { get; set; }
        public string Contato { get; set; }
        public string Telefone { get; set; }
        public string Celular { get; set; }
        public string Fax { get; set; }
        public string EmailFinanceiro { get; set; }
        public string EmailComercial { get; set; }
        public string EmailDivulgacao { get; set; }
        public string Uf { get; set; }
        public string PontoDeVenda { get; set; }
        public string Gestor { get; set; }
        public DateTime DataCadastroGestor { get; set; }
        public string SellIn { get; set; }
        public DateTime DataCadastroSellIn { get; set; }
        public string StatusCallidus { get; set; }
        public string AtualEstrelagem { get; set; }
        public string Rede { get; set; }
        public string Canal { get; set; }
        public string CodigoCliente { get; set; }
        public string CodigoFornecedor { get; set; }
        public string MatriculaGerConta { get; set; }
        public string CodIbge { get; set; }
        public string UfLocalidadePdv { get; set; }
        public string Ddd { get; set; }
    }
}