// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.DataGRC
{
    public partial class ENVIO_CARTEIRA
    {
        public string RazaoSocial { get; set; }
        public string NomeFantasia { get; set; }
        public string Cidade { get; set; }
        public string Uf { get; set; }
        public string GERENTE_CONTAS { get; set; }
        public string MATRICULA_GERENTE_CONTAS { get; set; }
        public string Vendedor { get; set; }
        public string REDE { get; set; }
        public string Genero { get; set; }
        public string StatusCallidus { get; set; }
        public string TERRITORIO { get; set; }
        public string LoginSiebel { get; set; }
    }
}