// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.DataGRC
{
    public partial class fat_SET_
    {
        public string ORDEM_VEND { get; set; }
        public string CENT { get; set; }
        public string TPOV { get; set; }
        public string DESCRIÇÃO_DA_OV { get; set; }
        public double? CLIENTE { get; set; }
        public string NOME_DO_CLIENTE { get; set; }
        public string CPF_CNPJ { get; set; }
        public string MATERIAL { get; set; }
        public string DESCRIÇÃO { get; set; }
        public double? QTDE_FATURADA { get; set; }
        public string DATA_NF { get; set; }
        public string Nº_DE_SÉRIE { get; set; }
        public string ORDEM { get; set; }
        public string FORMA_PGT { get; set; }
        public string TPPED { get; set; }
        public string COND_PGT { get; set; }
        public double? VALOR_NF { get; set; }
        public double? RECEITA_BRUTA { get; set; }
        public double? DESCONTO { get; set; }
        public double? ICMS { get; set; }
        public double? PIS { get; set; }
        public double? COFINS { get; set; }
        public double? RECEITA_LÍQUIDA { get; set; }
        public double? CMV { get; set; }
        public double? MARGEM_BRUTA { get; set; }
        public string CENTRO_DE_CUSTO { get; set; }
        public string UF_CLIENTE { get; set; }
        public string GRUPO_CLIENTE { get; set; }
        public string CRIADO_POR { get; set; }
        public string MESANO { get; set; }
        public double? DIA { get; set; }
        public double? MES { get; set; }
        public double? ANO { get; set; }
        public DateTime? DATA_FORM { get; set; }
        public string MES_ANO_CRIAÇÃO_FATURA { get; set; }
    }
}