// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.DataGRC
{
    public partial class HEADCOUNT_LLPP
    {
        public double? Matricula { get; set; }
        public string Nome { get; set; }
        public string Regional { get; set; }
        public double? Unidade { get; set; }
        public string Area { get; set; }
        public double? Cod_Cargo { get; set; }
        public string Cargo { get; set; }
        public DateTime? Data_Admissao { get; set; }
        public string Status { get; set; }
        public string Tipo_de_ausencia_ou_presenca { get; set; }
        public string Inicio { get; set; }
        public string Fim { get; set; }
        public string Ano { get; set; }
        public string Mes { get; set; }
    }
}