// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vivo_Apps_API.DataGRC
{
    public partial class LOJAS_SCA_360
    {
        public string VENDEDOR { get; set; }
        public string UF { get; set; }
        public string DESCRICAO_LOJA { get; set; }
        public string RAZAO_SOCIAL { get; set; }
    }
}