// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vivo_Apps_API.DataGRC
{
    public partial class PERFIS_DANI
    {
        public string PERFIL_DANI { get; set; }
        public string CARGO { get; set; }
        public string SUBGRUPO { get; set; }
    }
}