// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vivo_Apps_API.DataGRC
{
    public partial class REGISTRO_DIVISAO
    {
        public int Id { get; set; }
        public string Divisao { get; set; }
        public string Ddd { get; set; }
        public string Uf { get; set; }
    }
}