// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.DataGRC
{
    public partial class TAB_MAN_GERENTE_CONTum
    {
        public string CPF_FINAL { get; set; }
        public string NOME_FINAL { get; set; }
        public bool? SELL_IN { get; set; }
        public string SITUAÇÃO { get; set; }
        public string CADASTRADO_NO_CALLIDUS { get; set; }
        public double? TELEFONE_FINAL { get; set; }
        public string EMAIL_FINAL { get; set; }
        public string REGIONAL { get; set; }
        public string SEXO { get; set; }
        public string CANAL_SAP { get; set; }
        public string CANAL { get; set; }
        public string GRUPO_VENDEDOR_UF { get; set; }
        public string LIBERADO_NO_SAP { get; set; }
        public string UF { get; set; }
        public string ESCRITORIO_DE_VENDAS { get; set; }
        public DateTime? DATA { get; set; }
        public string AREA_ATUAÇÃO { get; set; }
        public string MATRICULA { get; set; }
    }
}