// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vivo_Apps_API.DataGRC
{
    public partial class TAB_COLABORADORES_LLPP
    {
        public int Identificação { get; set; }
        public string Nome { get; set; }
        public string Adabas { get; set; }
        public string Matricula_Vivo { get; set; }
        public string Loja { get; set; }
        public DateTime? Data_Cadastro { get; set; }
        public DateTime? Data_Entrada { get; set; }
    }
}