// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vivo_Apps_API.DataGRC
{
    public partial class TAB_CADASTRO_GERAL_PDVS_COMPLETO_OUTRAS_REGIONAIS_AUX
    {
        public string Vendedor { get; set; }
        public double? Cnpj { get; set; }
        public string RazaoSocial { get; set; }
        public string NomeFantasia { get; set; }
        public string Regional { get; set; }
        public double? Ddd { get; set; }
        public string Uf { get; set; }
        public string StatusCallidus { get; set; }
        public string TERRITORIO { get; set; }
        public string MATRICULA_TERRITORIAL { get; set; }
        public string SELL_IN { get; set; }
        public double? MATRICULA_SELLIN { get; set; }
        public string GERENTE_CONTAS { get; set; }
        public string MATRICULA_GC { get; set; }
        public string TIPO { get; set; }
    }
}