// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.DataGRC
{
    public partial class TAB_LOGRADOUROS_E_CLASSIFICAÇÃO
    {
        public string DOM_FISCAL { get; set; }
        public string NOME_LOCAL { get; set; }
        public string Classficação_1 { get; set; }
        public string Classificação_2 { get; set; }
    }
}