// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.DataGRC
{
    public partial class TAB_DE_PARA_ADABAS_LOJAS_PROPRIA
    {
        public string COD_CREDENC { get; set; }
        public string NOME_ENT_ABR { get; set; }
        public string DOM_FISCAL { get; set; }
        public string COD_CREDENC_NOVO { get; set; }
    }
}