// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vivo_Apps_API.DataGRC
{
    public partial class TAB_CANAIS_RESUMO
    {
        public string DES_ACTIV { get; set; }
        public string DES_CAN_RES { get; set; }
    }
}