// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vivo_Apps_API.DataGRC
{
    public partial class TAB_CADASTRO_GERAL_PDVS_USUARIO_VIVO_SIM
    {
        public string CNPJ { get; set; }
        public DateTime? DATA_INICIO_CONTRATO { get; set; }
        public DateTime? DATA_FIM_CONTRATO { get; set; }
        public string RAZÃO_SOCIAL { get; set; }
        public string NOME_FANTASIA { get; set; }
        public string INSCRIÇÃO_ESTADUAL { get; set; }
        public int? OPTANTE_SIMPLES { get; set; }
        public string REGIONAL { get; set; }
        public string TERRITORIAL { get; set; }
        public string CEP { get; set; }
        public string ENDEREÇO { get; set; }
        public string BAIRRO_ { get; set; }
        public string CIDADE { get; set; }
        public string NUMERO { get; set; }
        public string COMPLEMENTO { get; set; }
        public string CONTATO { get; set; }
        public string TELEFONE { get; set; }
        public string CELULAR { get; set; }
        public string FAX { get; set; }
        public string E_MAIL_FINANCEIRO { get; set; }
        public string E_MAIL_COMERCIAL { get; set; }
        public string E_MAIL_DIVULGAÇÃO { get; set; }
        public string HOME_PAGE { get; set; }
        public string CODIGO_BANCO { get; set; }
        public string AGENCIA { get; set; }
        public string NUMERO_CONTA { get; set; }
        public string DIGITO_VERIFICADOR { get; set; }
        public string REGIÃO_GEOGRAFICA { get; set; }
        public string SETOR_ATIVIDADE { get; set; }
        public string ÁREA_DE_CREDITO { get; set; }
        public string ORGANIZAÇÃO_DE_COMPRAS { get; set; }
        public string ORGANIZAÇÃO_DE_VENDAS { get; set; }
        public string GRUPO_VENDEDOR_NOME_GC { get; set; }
        public string PAGADOR_FATURA { get; set; }
        public string RECEBEDOR_DA_MERCADORIA { get; set; }
        public string RECEBEDOR_FATURA { get; set; }
        public string CODIGO_VENDEDOR { get; set; }
        public string REGIONAL2 { get; set; }
        public string TERRITORIAL2 { get; set; }
        public string UF { get; set; }
        public string RECEBEDOR_DO_COMISSIONAMENTO { get; set; }
        public string PONTO_DE_VENDA { get; set; }
        public string GESTOR { get; set; }
        public DateTime? DATA_CADASTRO_GESTOR { get; set; }
        public string SELL_IN { get; set; }
        public DateTime? DATA_CADASTRO_SELL_IN { get; set; }
        public string STATUS_CALLIDUS { get; set; }
        public double? INSTANCIA { get; set; }
        public string ATIVIDADE { get; set; }
        public decimal? LIMITE { get; set; }
        public DateTime? PRAZO_LIMITE { get; set; }
        public double? MARGEM_APARELHO { get; set; }
        public double? MARGEM_CHIP { get; set; }
        public double? MARGEM__RECARGA { get; set; }
        public string CONDIÇÕES_DE_PAGAMENTO { get; set; }
        public string VPC__Sell_in_ou_Out_ { get; set; }
        public string ATUAL_ESTRELAGEM { get; set; }
        public DateTime? DATA_EFETI_CART_SELL_IN { get; set; }
        public DateTime? DATA_EFETI_CART_GESTOR { get; set; }
        public string CANAL_DISTRIBUIÇÃO { get; set; }
        public string VENDEDOR { get; set; }
        public string REDE { get; set; }
        public string CANAL { get; set; }
        public double? CÓDIGO_CLIENTE { get; set; }
        public double? CÓDIGO_FORNECEDOR { get; set; }
        public string MATRICULA_GER_CONTA { get; set; }
        public string COD_IBGE { get; set; }
        public string UF_LOCALIDADE_PDV { get; set; }
        public string IXOS { get; set; }
        public string DDD_GESTOR { get; set; }
        public string AREA_ATUAÇÃO_DDD_GESTOR { get; set; }
        public string GERENTE_TERRITORIAL { get; set; }
        public string MATRICULA_SELL_IN { get; set; }
        public string MATRICULA_TERRITORIAL { get; set; }
    }
}