// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.DataGRC
{
    public partial class TAB_PESSOA
    {
        public double? ANO { get; set; }
        public string MÊS { get; set; }
        public string STATUS { get; set; }
        public string MATRÍCULA { get; set; }
        public string USER_ID_SSFF { get; set; }
        public string NOME { get; set; }
        public string EMPRESA { get; set; }
        public double? CÓDIGO_EMPRESA { get; set; }
        public string NOME_EMPRESA { get; set; }
        public string CNPJ { get; set; }
        public string REGIONAL { get; set; }
        public string FILIAL { get; set; }
        public string SUBÁREA { get; set; }
        public double? CÓDIGO_UNIDADE_SAP { get; set; }
        public double? CÓDIGO_UNIDADE_SSFF { get; set; }
        public string ESTADO_COMERCIAL { get; set; }
        public string CIDADE_COMERCIAL { get; set; }
        public string BAIRRO_COMERCIAL { get; set; }
        public string ENDEREÇO_COMERCIAL { get; set; }
        public string NÚMERO_COMERCIAL { get; set; }
        public string COMPLEMENTO_COMERCIAL { get; set; }
        public string CEP_COMERCIAL { get; set; }
        public string VP { get; set; }
        public string DIRETORIA_1 { get; set; }
        public string DIRETORIA_2 { get; set; }
        public string DIRETORIA_3 { get; set; }
        public string GERÊNCIA_SR { get; set; }
        public string GERÊNCIA { get; set; }
        public string ÁREA { get; set; }
        public string SIGLA { get; set; }
        public string MATRÍCULA_GESTOR { get; set; }
        public string USER_ID_SSFF_GESTOR { get; set; }
        public string GESTOR { get; set; }
        public string E_MAIL_GESTOR { get; set; }
        public string CENTRO_DE_CUSTO { get; set; }
        public string OBJETO_DE_CUSTO { get; set; }
        public string CARGO { get; set; }
        public string CATEGORIA { get; set; }
        public string CÓDIGO_SUBGRUPO { get; set; }
        public double? CÓDIGO_CARGO_SSFF { get; set; }
        public string SUBGRUPO { get; set; }
        public string POSIÇÃO { get; set; }
        public double? POSIÇÃO_SAP { get; set; }
        public DateTime? ÚLTIMA_DATA_OCUPAÇÃO_POSIÇÃO { get; set; }
        public string LOJA { get; set; }
        public string CALL_CENTER { get; set; }
        public string ELEGÍVEL_AO_TELETRABALHO { get; set; }
        public DateTime? DATA_ADMISSÃO { get; set; }
        public DateTime? DATA_DESLIGAMENTO { get; set; }
        public double? TEMPO_DE_EMPRESA { get; set; }
        public string FAIXA_TEMPO_DE_EMPRESA { get; set; }
        public string AFASTAMENTO { get; set; }
        public DateTime? DATA_INÍCIO_AFASTAMENTO { get; set; }
        public DateTime? DATA_FIM_AFASTAMENTO { get; set; }
        public string ESTABILIDADE { get; set; }
        public DateTime? DATA_INÍCIO_ESTABILIDADE { get; set; }
        public DateTime? DATA_FIM_ESTABILIDADE { get; set; }
        public double? QTD_FILHOS { get; set; }
        public string FÉRIAS_NO_MÊS { get; set; }
        public DateTime? INÍCIO_FÉRIAS { get; set; }
        public DateTime? FIM_FÉRIAS { get; set; }
        public DateTime? INÍCIO_PRÓXIMAS_FÉRIAS { get; set; }
        public DateTime? FIM_PRÓXIMAS_FÉRIAS { get; set; }
        public string E_MAIL { get; set; }
        public string CELULAR { get; set; }
        public string CPF { get; set; }
        public string GÊNERO { get; set; }
        public DateTime? DATA_DE_NASCIMENTO { get; set; }
        public string IDADE { get; set; }
        public string FAIXA_DE_IDADE { get; set; }
        public string OBSERVACAO { get; set; }
        public string MODIFICADO { get; set; }
    }
}