// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vivo_Apps_API.DataGRC
{
    public partial class TAB_AG_CREDENCIADOS_DESCOBRE_PDV
    {
        public string ZAMP_ID { get; set; }
        public string COD_CREDENC { get; set; }
        public decimal? COD_ENT_VEND { get; set; }
        public decimal? COD_ALVO { get; set; }
        public string NOME_ENT { get; set; }
        public decimal? NUM_CGC { get; set; }
        public string NOME_ENT_ABR { get; set; }
        public string NUM_INSCR_EST { get; set; }
        public decimal? COD_CLI_SAP { get; set; }
        public string DOM_FISCAL { get; set; }
        public string NOME_BAIRRO { get; set; }
        public string NOME_LOCAL { get; set; }
        public string DES_REG { get; set; }
        public string NOM_CASC { get; set; }
        public decimal? COD_GESTOR { get; set; }
        public string NOME_GESTOR { get; set; }
        public string DES_SEC { get; set; }
        public string DES_GEN_ENT { get; set; }
        public string DES_ACTIV { get; set; }
        public string DES_REG_1 { get; set; }
        public string ESCV { get; set; }
        public string CNTR_DSTR { get; set; }
    }
}