// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vivo_Apps_API.DataGRC
{
    public partial class VIEW_GERENTE_TERRITORIO
    {
        public string MATRICULA { get; set; }
        public string NOME { get; set; }
    }
}