// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vivo_Apps_API.DataGRC
{
    public partial class VIEW_GERENTE_TERRITORIAL
    {
        public string DDD { get; set; }
        public string MATRICULA { get; set; }
        public string NOME { get; set; }
        public string AREA_ATUACAO_DDD { get; set; }
        public DateTime? DATA_EFETIVA_GESTAO { get; set; }
        public DateTime? DATA_CADASTRO { get; set; }
        public string STATUS { get; set; }
    }
}