// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.Data
{
    public partial class ACESSO
    {
        public ACESSO()
        {
            ACESSO_PERMISSAO_MENUs = new HashSet<ACESSO_PERMISSAO_MENU>();
        }

        public int idAcesso { get; set; }
        public string Login { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Regional { get; set; }
        public byte[] Senha { get; set; }
        public byte[] Imagem { get; set; }
        public string Status { get; set; }
        public bool? Primeiro_Acesso { get; set; }

        public virtual ICollection<ACESSO_PERMISSAO_MENU> ACESSO_PERMISSAO_MENUs { get; set; }
    }
}