// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.Data
{
    public partial class ACESSO_PERMISSAO_MENU
    {
        public int idPermissao { get; set; }
        public int idAcesso { get; set; }
        public string DescricaoMenu { get; set; }
        public string TipoAcesso { get; set; }
    }
}