// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vivo_Apps_API.Data
{
    public partial class ACESSO
    {
        public int idAcesso { get; set; }
        public string Login { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Regional { get; set; }
        public byte[] Senha { get; set; }
        public byte[] Imagem { get; set; }
        public string Status { get; set; }
        public bool? Primeiro_Acesso { get; set; }
    }
}