// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.Data
{
    public partial class ACESSOS_MOBILE_PERFIL
    {
        public string CARGO { get; set; }
        public string PERFIL { get; set; }
        public int? CREAT_FORMS { get; set; }
        public int ID { get; set; }
    }
}