// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.Data
{
    public partial class CADASTRO_GERENTE_TERRITORIO
    {
        public string DDD { get; set; }
        public string MATRICULA { get; set; }
        public string NOME { get; set; }
        public string AREA_ATUACAO_DDD { get; set; }
        public string DATA_EFETIVA_GESTAO { get; set; }
        public DateTime? DATA_CADASTRO { get; set; }
        public int ID { get; set; }
    }
}