// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vivo_Apps_API.Data
{
    public partial class CAMPOS_FILA
    {
        public int ID_CAMPOS { get; set; }
        public int ID_SUB_FILA { get; set; }
        public string CAMPO { get; set; }
        public string MASCARA { get; set; }
        public bool CAMPO_SUSPENSO { get; set; }
        public string REGIONAL { get; set; }
        public string DT_CRIACAO { get; set; }
        public bool STATUS_CAMPOS_FILA { get; set; }
        public int MAT_CRIADOR { get; set; }
    }
}