// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.Data
{
    public partial class carteira_demais_canais_rede_colaborador
    {
        public string REDE { get; set; }
        public string MATRICULA_1 { get; set; }
        public string MATRICULA_2 { get; set; }
        public string MATRICULA_3 { get; set; }
        public string MATRICULA_4 { get; set; }
        public string SAL { get; set; }
        public string Uf { get; set; }
        public string CANAL { get; set; }
        public string MATRICULA_5 { get; set; }
        public string MATRICULA_6 { get; set; }
        public string MATRICULA_7 { get; set; }
        public string MATRICULA_8 { get; set; }
        public string MATRICULA_9 { get; set; }
        public string MATRICULA_10 { get; set; }
        public string MATRICULA_11 { get; set; }
        public string MATRICULA_12 { get; set; }
        public string MATRICULA_13 { get; set; }
        public string MATRICULA_14 { get; set; }
        public string MATRICULA_15 { get; set; }
    }
}