// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vivo_Apps_API.Data
{
    public partial class Carteira_NE
    {
        public string Cnpj { get; set; }
        public string RazaoSocial { get; set; }
        public string NomeFantasia { get; set; }
        public string Uf { get; set; }
        public string GA___GG { get; set; }
        public string RE_GA { get; set; }
        public string GGP { get; set; }
        public string RE_GGP { get; set; }
        public string StatusCallidus { get; set; }
        public string Vendedor { get; set; }
        public string REDE { get; set; }
        public string Canal { get; set; }
        public double? DDD_LOCALIDADE_PDV { get; set; }
        public string Atividade { get; set; }
        public string AREA_ATUAÇÃO_DDD { get; set; }
        public string GV { get; set; }
        public string RE_GV { get; set; }
        public string LoginSiebel { get; set; }
        public string Cidade { get; set; }
        public string Bairro { get; set; }
        public string Cep { get; set; }
        public string Endereco { get; set; }
        public string Numero { get; set; }
        public string Complemento { get; set; }
        public string Data_Credenciamento { get; set; }
        public string Data_Descredenciamento { get; set; }
        public string Modelo_Loja { get; set; }
        public string Tipo_Loja { get; set; }
        public string Local_Loja { get; set; }
        public string GSS { get; set; }
        public string Qt_de_PA { get; set; }
        public string Metragem { get; set; }
        public string SEGMENTAÇÃO { get; set; }
        public string Estrelagem { get; set; }
        public string MT { get; set; }
        public string ANOMES { get; set; }
        public int ID { get; set; }
        public string NO_VIVO360 { get; set; }
        public string NO_VIVONEXT { get; set; }
        public string NO_GSS { get; set; }
        public string DT_MOD_CAD { get; set; }
        public string LOGIN_MOD_CAD { get; set; }
        public string DataInicioContrato { get; set; }
        public string DataFimContrato { get; set; }
        public string InscriçãoEstadual { get; set; }
        public string OptanteSimples { get; set; }
        public string Contato { get; set; }
        public string Telefone { get; set; }
        public string EmailFinanceiro { get; set; }
        public string EmailComercial { get; set; }
        public string EmailDivulgação { get; set; }
        public string CodigoBanco { get; set; }
        public string Banco { get; set; }
        public string Agencia { get; set; }
        public string NumeroConta { get; set; }
        public string DigitoVerificador { get; set; }
        public string SetorAtividade { get; set; }
        public string PontoVenda { get; set; }
        public string Genero { get; set; }
        public string CodigoCliente { get; set; }
        public string CodigoFornecedor { get; set; }
        public string Area { get; set; }
        public string Ixos { get; set; }
    }
}