// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vivo_Apps_API.Data
{
    public partial class CARTEIRA_DEMAIS_CANAI
    {
        public string Cnpj { get; set; }
        public string RazaoSocial { get; set; }
        public string NomeFantasia { get; set; }
        public string Uf { get; set; }
        public string GA { get; set; }
        public string GGP { get; set; }
        public string StatusCallidus { get; set; }
        public string Vendedor { get; set; }
        public string REDE { get; set; }
        public string Canal { get; set; }
        public string DDD_LOCALIDADE_PDV { get; set; }
        public string Atividade { get; set; }
        public string AREA_ATUACAO_DDD { get; set; }
        public string GV { get; set; }
        public string LoginSiebel { get; set; }
        public string Cidade { get; set; }
        public string Bairro { get; set; }
        public string Cep { get; set; }
        public string Endereco { get; set; }
        public string Numero { get; set; }
        public string Complemento { get; set; }
        public string Data_Credenciamento { get; set; }
        public string Data_Descredenciamento { get; set; }
        public string Modelo_Loja { get; set; }
        public string Tipo_Loja { get; set; }
        public string Local_Loja { get; set; }
        public string GSS { get; set; }
        public string Clusters { get; set; }
        public string Estrelagem { get; set; }
        public string MT { get; set; }
        public int Id { get; set; }
        public string ANOMES { get; set; }
        public DateTime? DataUltimaAlteracao { get; set; }
        public int? idAcesso { get; set; }
        public DateTime? DataSolicitacao { get; set; }
        public string DivisaoOrig { get; set; }
        public string MATRICULA_GV { get; set; }
        public string MATRICULA_GA { get; set; }
        public string MATRICULA_GGP { get; set; }
        public bool? ANOMES_ATUAL { get; set; }
        public string QtdPA { get; set; }
        public string Metragem { get; set; }
    }
}