// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.Data
{
    public partial class CONTROLE_DE_DEMANDAS_OPERADORE
    {
        public string LOGIN { get; set; }
        public string NOME { get; set; }
        public string NIVEL { get; set; }
        public string UF { get; set; }
    }
}