// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vivo_Apps_API.Data
{
    public partial class CONTROLE_DE_DEMANDAS_CHAMADO_RESPOSTum
    {
        public int ID { get; set; }
        public string RESPOSTA { get; set; }
        public int ID_CHAMADO { get; set; }
        public string MATRICULA_RESPONSAVEL { get; set; }
        public DateTime? DATA_RESPOSTA { get; set; }
    }
}