// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.Data
{
    public partial class CONTROLE_DE_DEMANDAS_CHAMADO
    {
        public CONTROLE_DE_DEMANDAS_CHAMADO()
        {
            CONTROLE_DE_DEMANDAS_CHAMADO_ARQUIVOs = new HashSet<CONTROLE_DE_DEMANDAS_CHAMADO_ARQUIVO>();
            CONTROLE_DE_DEMANDAS_CHAMADO_RESPOSTa = new HashSet<CONTROLE_DE_DEMANDAS_CHAMADO_RESPOSTum>();
        }

        public int ID { get; set; }
        public int? ID_CAMPOS_CHAMADO { get; set; }
        public int? ID_STATUS_CHAMADO { get; set; }
        public int ID_FILA_CHAMADO { get; set; }
        public string MATRICULA_RESPONSAVEL { get; set; }
        public string MATRICULA_SOLICITANTE { get; set; }
        public DateTime? DATA_ABERTURA { get; set; }
        public DateTime? DATA_FECHAMENTO { get; set; }
        public string MOTIVO_FECHAMENTO_SUPORTE { get; set; }
        public string PRIORIDADE { get; set; }
        public string REGIONAL { get; set; }
        public string PBI { get; set; }
        public string EMAIL_SECUNDARIO { get; set; }
        public string RESPONSAVEL_OUTRA_AREA { get; set; }

        public virtual CONTROLE_DE_DEMANDAS_CAMPOS_CHAMADO ID_CAMPOS_CHAMADONavigation { get; set; }
        public virtual CONTROLE_DE_DEMANDAS_FILA ID_FILA_CHAMADONavigation { get; set; }
        public virtual CONTROLE_DE_DEMANDAS_STATUS_CHAMADO ID_STATUS_CHAMADONavigation { get; set; }
        public virtual ICollection<CONTROLE_DE_DEMANDAS_CHAMADO_ARQUIVO> CONTROLE_DE_DEMANDAS_CHAMADO_ARQUIVOs { get; set; }
        public virtual ICollection<CONTROLE_DE_DEMANDAS_CHAMADO_RESPOSTum> CONTROLE_DE_DEMANDAS_CHAMADO_RESPOSTa { get; set; }
    }
}