// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vivo_Apps_API.Data
{
    public partial class CONTROLE_DE_DEMANDAS_FILA
    {
        public int ID { get; set; }
        public string FILA { get; set; }
        public string ADD_CAMPOS_AUTOMATICOS { get; set; }
        public string MAT_QUEM_CRIOU { get; set; }
        public string ADD_CAMPOS_MUNICIPIOS { get; set; }
        public string TIPO_CHAMADO { get; set; }
        public string REGIONAL { get; set; }
        public string ADD_PDV_DESTINO { get; set; }
    }
}