// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.Data
{
    public partial class CONTROLE_DE_DEMANDAS_SUGESTOES_NOMES_CAMPO
    {
        public string CAMPO { get; set; }
        public string MASCARA { get; set; }
    }
}