// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.Data
{
    public partial class CONTROLE_DEMANDAS_ARQUIVOS_RESPOSTum
    {
        public int ID { get; set; }
        public int ID_RESPOSTA { get; set; }
        public string NOME_ARQUIVO { get; set; }
        public string EXT_ARQUIVO { get; set; }
        public byte[] ARQUIVO { get; set; }
    }
}