// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.Data
{
    public partial class CONTROLE_DE_DEMANDAS_CAMPOS_CHAMADO
    {
        public int ID { get; set; }
        public int ID_CHAMADO { get; set; }
    }
}