// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.Data
{
    public partial class CONTROLE_DE_DEMANDAS_RESPONSAVEL_FILA
    {
        public string MATRICULA_RESPONSAVEL { get; set; }
        public int ID_FILA_CHAMADO { get; set; }
    }
}