// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.Data
{
    public partial class CONTROLE_DE_DEMANDAS_STATUS_CHAMADO
    {
        public CONTROLE_DE_DEMANDAS_STATUS_CHAMADO()
        {
            CONTROLE_DE_DEMANDAS_CHAMADOs = new HashSet<CONTROLE_DE_DEMANDAS_CHAMADO>();
            CONTROLE_DE_DEMANDAS_RELACAO_STATUS_CHAMADOs = new HashSet<CONTROLE_DE_DEMANDAS_RELACAO_STATUS_CHAMADO>();
        }

        public int ID { get; set; }
        public int ID_CHAMADO { get; set; }

        public virtual ICollection<CONTROLE_DE_DEMANDAS_CHAMADO> CONTROLE_DE_DEMANDAS_CHAMADOs { get; set; }
        public virtual ICollection<CONTROLE_DE_DEMANDAS_RELACAO_STATUS_CHAMADO> CONTROLE_DE_DEMANDAS_RELACAO_STATUS_CHAMADOs { get; set; }
    }
}