// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vivo_Apps_API.Data
{
    public partial class CONTROLE_DE_DEMANDAS_RELACAO_CAMPOS_CHAMADO_BKP
    {
        public int ID_CAMPOS_CHAMADO { get; set; }
        public string CAMPO { get; set; }
        public string VALOR { get; set; }
    }
}