// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.Data
{
    public partial class CONTROLE_DE_DEMANDAS_RELACAO_STATUS_CHAMADO
    {
        public int ID_STATUS_CHAMADO { get; set; }
        public string STATUS { get; set; }
        public DateTime DATA { get; set; }
        public string MAT_QUEM_REDIRECIONOU { get; set; }
        public int ID { get; set; }
        public string ID_RESPOSTA { get; set; }

        public virtual CONTROLE_DE_DEMANDAS_STATUS_CHAMADO ID_STATUS_CHAMADONavigation { get; set; }
    }
}