// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.Data
{
    public partial class CREDENCIAMENTO_PROSPECT
    {
        public int ID { get; set; }
        public string MATRICULA_SOLICITANTE { get; set; }
        public string UF { get; set; }
        public string DDD { get; set; }
        public string RAZAO_SOCIAL { get; set; }
        public string CANAL_CREDENCIAMENTO { get; set; }
        public string OBSERVACAO { get; set; }
        public DateTime? DATA_ABERTURA { get; set; }
        public string DATA_PREVISTA_CREDENCIAMENTO { get; set; }
        public string REGIONAL { get; set; }
        public DateTime? data_ultimo_status { get; set; }
        public string ultimo_status { get; set; }
        public DateTime? DATA_TORNOU_CREDENCIAMENTO { get; set; }
        public string CIDADE { get; set; }
        public string TIPO_REVENDA { get; set; }
    }
}