// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.Data
{
    public partial class FIXA_BASE_PRUMA
    {
        public int ID { get; set; }
        public int? COD_PREDIO { get; set; }
        public string NOM_PREDIO { get; set; }
        public int? COD_CONDOMINIO { get; set; }
        public string NOM_CONDOMINIO { get; set; }
        public string DAT_INSERCAO { get; set; }
        public string NOM_CONTVIST { get; set; }
        public string NOM_CONTOBRAEXT { get; set; }
        public string SEGMENTO { get; set; }
        public string TIPO { get; set; }
        public string LOGRADOURO { get; set; }
        public int? NUMERO { get; set; }
        public string CIDADE { get; set; }
        public string ESTEIRA { get; set; }
        public string MOTIVO { get; set; }
        public string DAT_LIB_COMERCIAL { get; set; }
        public int? CUSTO_OBRA_EXT { get; set; }
        public int? BLOCOS { get; set; }
        public int? QTD_APARTAMENTO { get; set; }
        public string PROSPECTOR { get; set; }
        public int? CEP { get; set; }
        public string DATA_ESTEIRA { get; set; }
        public int? OBRA_RUA_ESPECIAL { get; set; }
        public int? OBRA_PREDIO_ESPECIAL { get; set; }
        public int? VAL_QTDVISTAG { get; set; }
        public string PRIORIDADE { get; set; }
        public string REDE { get; set; }
        public string ARMARIO { get; set; }
        public string STATUS { get; set; }
        public string CAIXA { get; set; }
        public string UF { get; set; }
        public string BAIRRO { get; set; }
        public string REGIONAL { get; set; }
        public string COMPLEMENTO { get; set; }
        public int? CASAS_CONSTRUIDAS { get; set; }
        public string ARMARIO_COBRE { get; set; }
        public string CONCORRENCIA { get; set; }
        public string CLASSE { get; set; }
        public string CEP_NUM { get; set; }
    }
}