// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vivo_Apps_API.Data
{
    public partial class HISTORICO_ACESSOS_MOBILE_PENDENTE
    {
        public int ID { get; set; }
        public int ID_ACESSOS_PENDENTE { get; set; }
        public string MATRICULA { get; set; }
        public string RESPOSTA { get; set; }
        public string STATUS { get; set; }
        public string DATA { get; set; }
    }
}