// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vivo_Apps_API.Data
{
    public partial class JORNADA_BD_TEMAS_SUB_TEMA
    {
        public int ID_SUB_TEMAS { get; set; }
        public string SUB_TEMAS { get; set; }
        public int? ID_TEMAS { get; set; }
        public string TEMAS { get; set; }
    }
}