// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.Data
{
    public partial class JORNADA_BD_HIERARQUIum
    {
        public int ID { get; set; }
        public string ADABAS { get; set; }
        public string NOME_FANTASIA { get; set; }
        public string REDE { get; set; }
        public string UF { get; set; }
        public int? DDD { get; set; }
        public string REGIONAL { get; set; }
        public bool? STATUS { get; set; }
        public string LOGIN_MOD { get; set; }
        public string DT_MOD { get; set; }
    }
}