// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.Data
{
    public partial class JORNADA_BD_RELACAO_HISTORICO
    {
        public int ID_PROVA { get; set; }
        public string LOGIN_MOD { get; set; }
        public string DT_MOD { get; set; }
    }
}