// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.Data
{
    public partial class JORNADA_BD_QUESTION_HISTORICO
    {
        public int ID_PROVA { get; set; }
        public int? ID_QUESTION { get; set; }
        public string CANAL { get; set; }
        public string DT_CRIACAO { get; set; }
        public string ID_CRIADOR { get; set; }
        public string CARGO { get; set; }
        public int? CADERNO { get; set; }
        public string TP_FORMS { get; set; }
        public string DT_INICIO_AVALIACAO { get; set; }
        public string DT_FINALIZACAO { get; set; }
        public string FIXA { get; set; }
    }
}