// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vivo_Apps_API.Data
{
    public partial class JORNADA_BD_CARGOS_CANAL
    {
        public double? ID { get; set; }
        public string CARGO { get; set; }
        public double? ID_CANAL { get; set; }
        public string CANAL { get; set; }
    }
}