// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.Data
{
    public partial class JORNADA_BD_ANSWER_ALTERNATIVA
    {
        public int ID_ALTERNATIVA { get; set; }
        public string ALTERNATIVA { get; set; }
        public int? ID_QUESTION { get; set; }
        public string STATUS_ALTERNATIVA { get; set; }
    }
}