// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vivo_Apps_API.Data
{
    public partial class JORNADA_BD_ANSWER_ALTERNATIVA
    {
        public int ID_ALTERNATIVA { get; set; }
        public string ALTERNATIVA { get; set; }
        public int? ID_QUESTION { get; set; }
        public bool? STATUS_ALTERNATIVA { get; set; }
        public int? PESO { get; set; }
        public bool? RESPOSTA_CORRETA { get; set; }
    }
}