// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vivo_Apps_API.Data
{
    public partial class PERFIL_VIVO_TASK
    {
        public int ID { get; set; }
        public string CARGO { get; set; }
        public int? VIVO_MAIS { get; set; }
        public int? RTCZ { get; set; }
        public int? FIXA { get; set; }
    }
}