// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.Data
{
    public partial class PERFIL_PLATAFORMAS_VIVO
    {
        public int ID_PERFIL { get; set; }
        public string Perfil { get; set; }
        public string obs { get; set; }
        public string CARGO { get; set; }
    }
}