// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.Data
{
    public partial class PERFIL_USUARIO_PENDENTE
    {
        public int ID { get; set; }
        public int? ID_ACESSO_PENDENTE { get; set; }
        public int? ID_PERFIL { get; set; }
    }
}