// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vivo_Apps_API.Data
{
    public partial class SUB_FILA
    {
        public int ID_SUB_FILA { get; set; }
        public string NOME_SUB_FILA { get; set; }
        public string REGIONAL { get; set; }
        public bool CAMPOS_AUTO { get; set; }
        public bool CAMPOS_IDENT_USER { get; set; }
        public bool STATUS_SUB_FILA { get; set; }
        public int? MAT_CRIADOR { get; set; }
        public int ID_TIPO_FILA { get; set; }
        public string DATA_CRIACAO { get; set; }
        public int? ID_ANTIGO { get; set; }
    }
}