// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.Data
{
    public partial class TAB_PESSOAS_SUPORTE
    {
        public double? MATRÍCULA { get; set; }
        public string NAME { get; set; }
        public string CARGO { get; set; }
        public string EMAIL { get; set; }
        public double? TELEFONE { get; set; }
        public int ID { get; set; }
    }
}