// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vivo_Apps_API.Data
{
    public partial class TIPO_FILA
    {
        public int ID { get; set; }
        public string NOME_TIPO_FILA { get; set; }
        public string REGIONAL { get; set; }
        public bool STATUS_TIPO_FILA { get; set; }
        public int MAT_CRIADOR { get; set; }
        public string DT_CRIACAO { get; set; }
    }
}