// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_Vivo_Apps.Data
{
    public partial class VALORES_CAMPOS_SUSPENSO
    {
        public int ID_VALORES { get; set; }
        public string VALOR { get; set; }
        public int ID_CAMPOS { get; set; }
    }
}