// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Vivo_Apps_API.Data
{
    public partial class Vivo_MAISContext : DbContext
    {
        public Vivo_MAISContext()
        {
        }

        public Vivo_MAISContext(DbContextOptions<Vivo_MAISContext> options)
            : base(options)
        {
        }

        public virtual DbSet<ACESSO> ACESSOs { get; set; }
        public virtual DbSet<ACESSOS_MOBILE> ACESSOS_MOBILEs { get; set; }
        public virtual DbSet<ACESSOS_MOBILE_PENDENTE> ACESSOS_MOBILE_PENDENTEs { get; set; }
        public virtual DbSet<ACESSO_PERMISSAO_MENU> ACESSO_PERMISSAO_MENUs { get; set; }
        public virtual DbSet<ACESSO_TERCEIRO> ACESSO_TERCEIROs { get; set; }
        public virtual DbSet<CADASTRO_GERENTE_TERRITORIO> CADASTRO_GERENTE_TERRITORIOs { get; set; }
        public virtual DbSet<CADASTRO_PDV> CADASTRO_PDVs { get; set; }
        public virtual DbSet<CAMPOS_FILA> CAMPOS_FILAs { get; set; }
        public virtual DbSet<CONTROLE_DEMANDAS_ARQUIVOS_RESPOSTum> CONTROLE_DEMANDAS_ARQUIVOS_RESPOSTAs { get; set; }
        public virtual DbSet<CONTROLE_DE_DEMANDAS_ARQUIVOS_RESPOSTum> CONTROLE_DE_DEMANDAS_ARQUIVOS_RESPOSTAs { get; set; }
        public virtual DbSet<CONTROLE_DE_DEMANDAS_CAMPOS_CHAMADO> CONTROLE_DE_DEMANDAS_CAMPOS_CHAMADOs { get; set; }
        public virtual DbSet<CONTROLE_DE_DEMANDAS_CAMPOS_FILA> CONTROLE_DE_DEMANDAS_CAMPOS_FILAs { get; set; }
        public virtual DbSet<CONTROLE_DE_DEMANDAS_CAMPO_COMBOBOX_FILA> CONTROLE_DE_DEMANDAS_CAMPO_COMBOBOX_FILAs { get; set; }
        public virtual DbSet<CONTROLE_DE_DEMANDAS_CAMPO_LISTA_ICCID> CONTROLE_DE_DEMANDAS_CAMPO_LISTA_ICCIDs { get; set; }
        public virtual DbSet<CONTROLE_DE_DEMANDAS_CHAMADO> CONTROLE_DE_DEMANDAS_CHAMADOs { get; set; }
        public virtual DbSet<CONTROLE_DE_DEMANDAS_CHAMADO_ARQUIVO> CONTROLE_DE_DEMANDAS_CHAMADO_ARQUIVOs { get; set; }
        public virtual DbSet<CONTROLE_DE_DEMANDAS_CHAMADO_RESPOSTum> CONTROLE_DE_DEMANDAS_CHAMADO_RESPOSTAs { get; set; }
        public virtual DbSet<CONTROLE_DE_DEMANDAS_FILA> CONTROLE_DE_DEMANDAS_FILAs { get; set; }
        public virtual DbSet<CONTROLE_DE_DEMANDAS_OPERADORE> CONTROLE_DE_DEMANDAS_OPERADOREs { get; set; }
        public virtual DbSet<CONTROLE_DE_DEMANDAS_RELACAO_CAMPOS_CHAMADO> CONTROLE_DE_DEMANDAS_RELACAO_CAMPOS_CHAMADOs { get; set; }
        public virtual DbSet<CONTROLE_DE_DEMANDAS_RELACAO_CAMPOS_CHAMADO_BKP> CONTROLE_DE_DEMANDAS_RELACAO_CAMPOS_CHAMADO_BKPs { get; set; }
        public virtual DbSet<CONTROLE_DE_DEMANDAS_RELACAO_ITENS_CAMPO_COMBOBOX_FILA> CONTROLE_DE_DEMANDAS_RELACAO_ITENS_CAMPO_COMBOBOX_FILAs { get; set; }
        public virtual DbSet<CONTROLE_DE_DEMANDAS_RELACAO_STATUS_CHAMADO> CONTROLE_DE_DEMANDAS_RELACAO_STATUS_CHAMADOs { get; set; }
        public virtual DbSet<CONTROLE_DE_DEMANDAS_RESPONSAVEL_FILA> CONTROLE_DE_DEMANDAS_RESPONSAVEL_FILAs { get; set; }
        public virtual DbSet<CONTROLE_DE_DEMANDAS_STATUS_CHAMADO> CONTROLE_DE_DEMANDAS_STATUS_CHAMADOs { get; set; }
        public virtual DbSet<CONTROLE_DE_DEMANDAS_SUGESTOES_NOMES_CAMPO> CONTROLE_DE_DEMANDAS_SUGESTOES_NOMES_CAMPOs { get; set; }
        public virtual DbSet<CREDENCIAMENTO_PROSPECT> CREDENCIAMENTO_PROSPECTs { get; set; }
        public virtual DbSet<Carteira_NE> Carteira_NEs { get; set; }
        public virtual DbSet<FIXA_BASE_PRUMA> FIXA_BASE_PRUMAs { get; set; }
        public virtual DbSet<FIXA_VIEW_PAINEL_DE_ROTA> FIXA_VIEW_PAINEL_DE_ROTAs { get; set; }
        public virtual DbSet<HISTORICO_ACESSOS_MOBILE_PENDENTE> HISTORICO_ACESSOS_MOBILE_PENDENTEs { get; set; }
        public virtual DbSet<JORNADA_BD_ANSWER_ALTERNATIVA> JORNADA_BD_ANSWER_ALTERNATIVAs { get; set; }
        public virtual DbSet<JORNADA_BD_ANSWER_AVALIACAO> JORNADA_BD_ANSWER_AVALIACAOs { get; set; }
        public virtual DbSet<JORNADA_BD_AVALIACAO_RETORNO> JORNADA_BD_AVALIACAO_RETORNOs { get; set; }
        public virtual DbSet<JORNADA_BD_CARGOS_CANAL> JORNADA_BD_CARGOS_CANALs { get; set; }
        public virtual DbSet<JORNADA_BD_QUESTION> JORNADA_BD_QUESTIONs { get; set; }
        public virtual DbSet<JORNADA_BD_QUESTION_HISTORICO> JORNADA_BD_QUESTION_HISTORICOs { get; set; }
        public virtual DbSet<JORNADA_BD_TEMAS_SUB_TEMA> JORNADA_BD_TEMAS_SUB_TEMAs { get; set; }
        public virtual DbSet<PERFIL_VIVO_TASK> PERFIL_VIVO_TASKs { get; set; }
        public virtual DbSet<SUB_FILA> SUB_FILAs { get; set; }
        public virtual DbSet<TAB_PESSOAS_SUPORTE> TAB_PESSOAS_SUPORTEs { get; set; }
        public virtual DbSet<TIPO_FILA> TIPO_FILAs { get; set; }
        public virtual DbSet<VALORES_CAMPOS_SUSPENSO> VALORES_CAMPOS_SUSPENSOs { get; set; }
        public virtual DbSet<carteira_demais_canais_rede_colaborador> carteira_demais_canais_rede_colaboradors { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=10.124.100.153;Initial Catalog=Vivo_MAIS;User ID=RegionalNE;Password=RegionalNEvivo2019;TrustServerCertificate=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.UseCollation("Latin1_General_CI_AS");

            modelBuilder.Entity<ACESSO>(entity =>
            {
                entity.HasKey(e => e.idAcesso)
                    .HasName("PK__ACESSO__CAAB807D0519C6AF");

                entity.ToTable("ACESSO");

                entity.Property(e => e.Email)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.Login)
                    .IsRequired()
                    .HasMaxLength(45)
                    .IsUnicode(false);

                entity.Property(e => e.Nome)
                    .IsRequired()
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.Regional)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Senha).HasMaxLength(50);

                entity.Property(e => e.Status)
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<ACESSOS_MOBILE>(entity =>
            {
                entity.ToTable("ACESSOS_MOBILE");

                entity.Property(e => e.CANAL).IsUnicode(false);

                entity.Property(e => e.CARGO).IsUnicode(false);

                entity.Property(e => e.CPF).IsUnicode(false);

                entity.Property(e => e.DT_MOD)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.EMAIL)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.LOGIN_MOD)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.MATRICULA)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.NOME).IsUnicode(false);

                entity.Property(e => e.OBS).IsUnicode(false);

                entity.Property(e => e.PDV).IsUnicode(false);

                entity.Property(e => e.REGIONAL)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.SENHA)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.TP_AFASTAMENTO)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.UF).IsUnicode(false);
            });

            modelBuilder.Entity<ACESSOS_MOBILE_PENDENTE>(entity =>
            {
                entity.ToTable("ACESSOS_MOBILE_PENDENTE");

                entity.Property(e => e.CANAL).IsUnicode(false);

                entity.Property(e => e.CARGO).IsUnicode(false);

                entity.Property(e => e.CPF)
                    .HasMaxLength(150)
                    .IsUnicode(false);

                entity.Property(e => e.DT_PRIMEIRO_RETORNO)
                    .HasMaxLength(150)
                    .IsUnicode(false);

                entity.Property(e => e.DT_RETORNO)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.DT_SOLICITACAO)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.EMAIL)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.LOGIN_RESPONSAVEL)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.LOGIN_SOLICITANTE)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.MATRICULA)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.NOME).IsUnicode(false);

                entity.Property(e => e.PDV)
                    .HasMaxLength(150)
                    .IsUnicode(false);

                entity.Property(e => e.REGIONAL)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.SENHA)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.STATUS)
                    .HasMaxLength(150)
                    .IsUnicode(false);

                entity.Property(e => e.TIPO)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.UF).IsUnicode(false);
            });

            modelBuilder.Entity<ACESSO_PERMISSAO_MENU>(entity =>
            {
                entity.HasKey(e => e.idPermissao)
                    .HasName("PK__ACESSO_P__7FFFCF600DAF0CB0");

                entity.ToTable("ACESSO_PERMISSAO_MENU");

                entity.Property(e => e.DescricaoMenu)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.TipoAcesso)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<ACESSO_TERCEIRO>(entity =>
            {
                entity.ToTable("ACESSO_TERCEIROS");

                entity.Property(e => e.Acao)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.AceiteSenha)
                    .HasMaxLength(150)
                    .IsUnicode(false);

                entity.Property(e => e.Adabas)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Area)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Bairro)
                    .HasMaxLength(150)
                    .IsUnicode(false);

                entity.Property(e => e.Celular)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Cep)
                    .HasMaxLength(150)
                    .IsUnicode(false);

                entity.Property(e => e.Cidade)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.CidadePrestServico)
                    .HasMaxLength(150)
                    .IsUnicode(false);

                entity.Property(e => e.Cnpj)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Complemento)
                    .HasMaxLength(150)
                    .IsUnicode(false);

                entity.Property(e => e.Cpf)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.DataCadastro).HasColumnType("datetime");

                entity.Property(e => e.DataContratoFim)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.DataContratoInicio)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.DataExtracao).HasColumnType("datetime");

                entity.Property(e => e.DataFinalizacao).HasColumnType("datetime");

                entity.Property(e => e.DataMatricula).HasColumnType("datetime");

                entity.Property(e => e.DataNascimento).HasColumnType("datetime");

                entity.Property(e => e.DataStatus).HasColumnType("datetime");

                entity.Property(e => e.Ddd)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.EMAILPESSOAL)
                    .HasMaxLength(500)
                    .IsUnicode(false);

                entity.Property(e => e.Email)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Estado)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.EstadoPrestServico)
                    .HasMaxLength(150)
                    .IsUnicode(false);

                entity.Property(e => e.Funcao)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.GESTORLIDER)
                    .HasMaxLength(150)
                    .IsUnicode(false);

                entity.Property(e => e.Login)
                    .HasMaxLength(150)
                    .IsUnicode(false);

                entity.Property(e => e.Matricula)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.MobileToken).HasColumnType("datetime");

                entity.Property(e => e.Nome)
                    .IsRequired()
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.NomeContato)
                    .IsRequired()
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.NomeMae)
                    .HasMaxLength(150)
                    .IsUnicode(false);

                entity.Property(e => e.Numero)
                    .HasMaxLength(150)
                    .IsUnicode(false);

                entity.Property(e => e.Obs)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.OrgaoEmissor)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Origem)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.PIS)
                    .HasMaxLength(60)
                    .IsUnicode(false);

                entity.Property(e => e.Perfil)
                    .HasMaxLength(150)
                    .IsUnicode(false);

                entity.Property(e => e.Regional)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.RejeitarSenha).HasColumnType("datetime");

                entity.Property(e => e.Rg)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Rua)
                    .HasMaxLength(150)
                    .IsUnicode(false);

                entity.Property(e => e.Senha)
                    .HasMaxLength(150)
                    .IsUnicode(false);

                entity.Property(e => e.Sexo)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Sobrenome)
                    .IsRequired()
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.Status)
                    .HasMaxLength(150)
                    .IsUnicode(false);

                entity.Property(e => e.SubArea)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.SubGrupo)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TELEFONEPESSOAL)
                    .HasMaxLength(500)
                    .IsUnicode(false);

                entity.Property(e => e.Telefone)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TipoAcesso)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<CADASTRO_GERENTE_TERRITORIO>(entity =>
            {
                entity.ToTable("CADASTRO_GERENTE_TERRITORIO");

                entity.Property(e => e.AREA_ATUACAO_DDD).HasMaxLength(255);

                entity.Property(e => e.DATA_CADASTRO).HasColumnType("datetime");

                entity.Property(e => e.DATA_EFETIVA_GESTAO)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.DDD).HasMaxLength(255);

                entity.Property(e => e.MATRICULA).HasMaxLength(255);

                entity.Property(e => e.NOME).HasMaxLength(255);
            });

            modelBuilder.Entity<CADASTRO_PDV>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("CADASTRO_PDV");

                entity.Property(e => e.ADMINISTRACAO).IsUnicode(false);

                entity.Property(e => e.AGENCIA).HasMaxLength(255);

                entity.Property(e => e.AREA_ATUAÇÃO_DDD_GESTOR)
                    .HasMaxLength(255)
                    .HasColumnName("AREA ATUAÇÃO DDD GESTOR");

                entity.Property(e => e.ASSINATURA_NO_CONTRATO_VIVO).IsUnicode(false);

                entity.Property(e => e.ATIVIDADE).HasMaxLength(255);

                entity.Property(e => e.ATUAL_ESTRELAGEM)
                    .HasMaxLength(255)
                    .HasColumnName("ATUAL ESTRELAGEM");

                entity.Property(e => e.BAIRRO_)
                    .HasMaxLength(255)
                    .HasColumnName("BAIRRO ");

                entity.Property(e => e.CANAL).HasMaxLength(255);

                entity.Property(e => e.CANAL_DISTRIBUIÇÃO)
                    .HasMaxLength(255)
                    .HasColumnName("CANAL DISTRIBUIÇÃO");

                entity.Property(e => e.CELULAR).HasMaxLength(255);

                entity.Property(e => e.CEP).HasMaxLength(255);

                entity.Property(e => e.CIDADE).HasMaxLength(255);

                entity.Property(e => e.CNPJ).HasMaxLength(255);

                entity.Property(e => e.CODIGO_BANCO)
                    .HasMaxLength(255)
                    .HasColumnName("CODIGO BANCO");

                entity.Property(e => e.CODIGO_VENDEDOR)
                    .HasMaxLength(255)
                    .HasColumnName("CODIGO VENDEDOR");

                entity.Property(e => e.COD_IBGE).HasMaxLength(255);

                entity.Property(e => e.COMPLEMENTO).HasMaxLength(255);

                entity.Property(e => e.CONDIÇÕES_DE_PAGAMENTO)
                    .HasMaxLength(255)
                    .HasColumnName("CONDIÇÕES DE PAGAMENTO");

                entity.Property(e => e.CONTATO).HasMaxLength(255);

                entity.Property(e => e.CPF).IsUnicode(false);

                entity.Property(e => e.CPF2).IsUnicode(false);

                entity.Property(e => e.CPF3).IsUnicode(false);

                entity.Property(e => e.CPF4).IsUnicode(false);

                entity.Property(e => e.CÓDIGO_CLIENTE).HasColumnName("CÓDIGO CLIENTE");

                entity.Property(e => e.CÓDIGO_FORNECEDOR).HasColumnName("CÓDIGO FORNECEDOR");

                entity.Property(e => e.DATA_CADASTRO_GESTOR).HasColumnType("datetime");

                entity.Property(e => e.DATA_CADASTRO_SELL_IN).HasColumnType("datetime");

                entity.Property(e => e.DATA_EFETI_CART_GESTOR).HasColumnType("datetime");

                entity.Property(e => e.DATA_EFETI_CART_SELL_IN).HasColumnType("datetime");

                entity.Property(e => e.DATA_ENVIO).IsUnicode(false);

                entity.Property(e => e.DATA_FIM_CONTRATO)
                    .HasColumnType("datetime")
                    .HasColumnName("DATA FIM CONTRATO");

                entity.Property(e => e.DATA_INICIO_CONTRATO)
                    .HasColumnType("datetime")
                    .HasColumnName("DATA INICIO CONTRATO");

                entity.Property(e => e.DATA_NOVO_GESTOR).HasColumnType("datetime");

                entity.Property(e => e.DATA_NOVO_TERRITORIAL).HasColumnType("datetime");

                entity.Property(e => e.DATA_RECEBIMENTO).IsUnicode(false);

                entity.Property(e => e.DDD_GESTOR)
                    .HasMaxLength(255)
                    .HasColumnName("DDD GESTOR");

                entity.Property(e => e.DIGITO_VERIFICADOR)
                    .HasMaxLength(255)
                    .HasColumnName("DIGITO VERIFICADOR");

                entity.Property(e => e.DMS).IsUnicode(false);

                entity.Property(e => e.DRN).IsUnicode(false);

                entity.Property(e => e.ENDEREÇO).HasMaxLength(255);

                entity.Property(e => e.E_MAIL_COMERCIAL)
                    .HasMaxLength(255)
                    .HasColumnName("E-MAIL COMERCIAL");

                entity.Property(e => e.E_MAIL_DIVULGAÇÃO)
                    .HasMaxLength(255)
                    .HasColumnName("E-MAIL DIVULGAÇÃO");

                entity.Property(e => e.E_MAIL_FINANCEIRO)
                    .HasMaxLength(255)
                    .HasColumnName("E-MAIL FINANCEIRO");

                entity.Property(e => e.FAX).HasMaxLength(255);

                entity.Property(e => e.GERENTE_TERRITORIAL)
                    .HasMaxLength(255)
                    .HasColumnName("GERENTE TERRITORIAL");

                entity.Property(e => e.GESTOR).HasMaxLength(255);

                entity.Property(e => e.GRUPO_VENDEDOR_NOME_GC)
                    .HasMaxLength(255)
                    .HasColumnName("GRUPO VENDEDOR/NOME GC");

                entity.Property(e => e.HOME_PAGE)
                    .HasMaxLength(255)
                    .HasColumnName("HOME PAGE");

                entity.Property(e => e.INSCRIÇÃO_ESTADUAL)
                    .HasMaxLength(255)
                    .HasColumnName("INSCRIÇÃO ESTADUAL");

                entity.Property(e => e.IXOS).HasMaxLength(255);

                entity.Property(e => e.LIMITE).HasColumnType("money");

                entity.Property(e => e.MARGEM_APARELHO).HasColumnName("MARGEM APARELHO");

                entity.Property(e => e.MARGEM_CHIP).HasColumnName("MARGEM CHIP");

                entity.Property(e => e.MARGEM__RECARGA).HasColumnName("MARGEM  RECARGA");

                entity.Property(e => e.MATRICULA_GER_CONTA).HasMaxLength(255);

                entity.Property(e => e.MATRICULA_SELL_IN)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.MES_LIBERACAO).HasMaxLength(15);

                entity.Property(e => e.MODELO_CONTRATO).IsUnicode(false);

                entity.Property(e => e.NOME_FANTASIA)
                    .HasMaxLength(255)
                    .HasColumnName("NOME FANTASIA");

                entity.Property(e => e.NOVO_GERENTE_TERRITORIAL)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.NOVO_GESTOR).HasMaxLength(255);

                entity.Property(e => e.NUMERO).HasMaxLength(255);

                entity.Property(e => e.NUMERO_CONTA)
                    .HasMaxLength(255)
                    .HasColumnName("NUMERO CONTA");

                entity.Property(e => e.OPTANTE_SIMPLES).HasColumnName("OPTANTE SIMPLES");

                entity.Property(e => e.ORGANIZAÇÃO_DE_COMPRAS)
                    .HasMaxLength(255)
                    .HasColumnName("ORGANIZAÇÃO DE COMPRAS");

                entity.Property(e => e.ORGANIZAÇÃO_DE_VENDAS)
                    .HasMaxLength(255)
                    .HasColumnName("ORGANIZAÇÃO DE VENDAS");

                entity.Property(e => e.PAGADOR_FATURA)
                    .HasMaxLength(255)
                    .HasColumnName("PAGADOR FATURA");

                entity.Property(e => e.PONTO_DE_VENDA)
                    .HasMaxLength(255)
                    .HasColumnName("PONTO DE VENDA");

                entity.Property(e => e.PRAZO_LIMITE)
                    .HasColumnType("datetime")
                    .HasColumnName("PRAZO LIMITE");

                entity.Property(e => e.RAZÃO_SOCIAL)
                    .HasMaxLength(255)
                    .HasColumnName("RAZÃO SOCIAL");

                entity.Property(e => e.RECEBEDOR_DA_MERCADORIA)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("RECEBEDOR DA MERCADORIA");

                entity.Property(e => e.RECEBEDOR_DO_COMISSIONAMENTO)
                    .HasMaxLength(255)
                    .HasColumnName("RECEBEDOR DO COMISSIONAMENTO");

                entity.Property(e => e.RECEBEDOR_FATURA)
                    .HasMaxLength(255)
                    .HasColumnName("RECEBEDOR FATURA");

                entity.Property(e => e.REDE).HasMaxLength(255);

                entity.Property(e => e.REGIONAL).HasMaxLength(255);

                entity.Property(e => e.REGIONAL2).HasMaxLength(255);

                entity.Property(e => e.REGIÃO_GEOGRAFICA)
                    .HasMaxLength(255)
                    .HasColumnName("REGIÃO GEOGRAFICA");

                entity.Property(e => e.SELL_IN)
                    .HasMaxLength(255)
                    .HasColumnName("SELL IN");

                entity.Property(e => e.SETOR_ATIVIDADE)
                    .HasMaxLength(255)
                    .HasColumnName("SETOR ATIVIDADE");

                entity.Property(e => e.SOCIO1).IsUnicode(false);

                entity.Property(e => e.SOCIO2).IsUnicode(false);

                entity.Property(e => e.SOCIO3).IsUnicode(false);

                entity.Property(e => e.SOCIO4).IsUnicode(false);

                entity.Property(e => e.STATUS_CALLIDUS)
                    .HasMaxLength(255)
                    .HasColumnName("STATUS CALLIDUS");

                entity.Property(e => e.TELEFONE).HasMaxLength(255);

                entity.Property(e => e.TERRITORIAL).HasMaxLength(255);

                entity.Property(e => e.TERRITORIAL2).HasMaxLength(255);

                entity.Property(e => e.TIPO_MINUTA).IsUnicode(false);

                entity.Property(e => e.UF).HasMaxLength(255);

                entity.Property(e => e.UF_LOCALIDADE_PDV).HasMaxLength(255);

                entity.Property(e => e.VENDEDOR).HasMaxLength(255);

                entity.Property(e => e.VIGENCIA_FIM).IsUnicode(false);

                entity.Property(e => e.VIGENCIA_INICIO).IsUnicode(false);

                entity.Property(e => e.VPC__Sell_in_ou_Out_)
                    .HasMaxLength(255)
                    .HasColumnName("VPC (Sell in ou Out)");

                entity.Property(e => e.ÁREA_DE_CREDITO)
                    .HasMaxLength(255)
                    .HasColumnName("ÁREA DE CREDITO");
            });

            modelBuilder.Entity<CAMPOS_FILA>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("CAMPOS_FILA");

                entity.Property(e => e.CAMPO)
                    .IsRequired()
                    .IsUnicode(false);

                entity.Property(e => e.DT_CRIACAO)
                    .IsRequired()
                    .IsUnicode(false);

                entity.Property(e => e.ID_CAMPOS).ValueGeneratedOnAdd();

                entity.Property(e => e.MASCARA)
                    .IsRequired()
                    .IsUnicode(false);

                entity.Property(e => e.REGIONAL)
                    .IsRequired()
                    .IsUnicode(false);
            });

            modelBuilder.Entity<CONTROLE_DEMANDAS_ARQUIVOS_RESPOSTum>(entity =>
            {
                entity.ToTable("CONTROLE_DEMANDAS_ARQUIVOS_RESPOSTA");

                entity.Property(e => e.ARQUIVO).IsRequired();

                entity.Property(e => e.EXT_ARQUIVO)
                    .IsRequired()
                    .IsUnicode(false);

                entity.Property(e => e.NOME_ARQUIVO)
                    .IsRequired()
                    .IsUnicode(false);
            });

            modelBuilder.Entity<CONTROLE_DE_DEMANDAS_ARQUIVOS_RESPOSTum>(entity =>
            {
                entity.ToTable("CONTROLE_DE_DEMANDAS_ARQUIVOS_RESPOSTA");

                entity.Property(e => e.EXT_ARQUIVO)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.NOME_CAMPO).IsUnicode(false);
            });

            modelBuilder.Entity<CONTROLE_DE_DEMANDAS_CAMPOS_CHAMADO>(entity =>
            {
                entity.ToTable("CONTROLE_DE_DEMANDAS_CAMPOS_CHAMADO");
            });

            modelBuilder.Entity<CONTROLE_DE_DEMANDAS_CAMPOS_FILA>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("CONTROLE_DE_DEMANDAS_CAMPOS_FILA");

                entity.Property(e => e.CAMPO)
                    .IsRequired()
                    .IsUnicode(false);

                entity.Property(e => e.MASCARA)
                    .HasMaxLength(255)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<CONTROLE_DE_DEMANDAS_CAMPO_COMBOBOX_FILA>(entity =>
            {
                entity.ToTable("CONTROLE_DE_DEMANDAS_CAMPO_COMBOBOX_FILA");

                entity.Property(e => e.CAMPO)
                    .IsRequired()
                    .IsUnicode(false);
            });

            modelBuilder.Entity<CONTROLE_DE_DEMANDAS_CAMPO_LISTA_ICCID>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("CONTROLE_DE_DEMANDAS_CAMPO_LISTA_ICCID");

                entity.Property(e => e.NR_ICCID)
                    .HasMaxLength(550)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<CONTROLE_DE_DEMANDAS_CHAMADO>(entity =>
            {
                entity.ToTable("CONTROLE_DE_DEMANDAS_CHAMADO");

                entity.Property(e => e.DATA_ABERTURA).HasColumnType("datetime");

                entity.Property(e => e.DATA_FECHAMENTO).HasColumnType("datetime");

                entity.Property(e => e.EMAIL_SECUNDARIO).IsUnicode(false);

                entity.Property(e => e.MATRICULA_RESPONSAVEL).IsUnicode(false);

                entity.Property(e => e.MATRICULA_SOLICITANTE).IsUnicode(false);

                entity.Property(e => e.MOTIVO_FECHAMENTO_SUPORTE).IsUnicode(false);

                entity.Property(e => e.PBI).IsUnicode(false);

                entity.Property(e => e.PRIORIDADE)
                    .HasMaxLength(550)
                    .IsUnicode(false);

                entity.Property(e => e.REGIONAL)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.RESPONSAVEL_OUTRA_AREA)
                    .HasMaxLength(128)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<CONTROLE_DE_DEMANDAS_CHAMADO_ARQUIVO>(entity =>
            {
                entity.ToTable("CONTROLE_DE_DEMANDAS_CHAMADO_ARQUIVOS");

                entity.Property(e => e.EXT_ARQUIVO)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.NOME_CAMPO).IsUnicode(false);
            });

            modelBuilder.Entity<CONTROLE_DE_DEMANDAS_CHAMADO_RESPOSTum>(entity =>
            {
                entity.ToTable("CONTROLE_DE_DEMANDAS_CHAMADO_RESPOSTA");

                entity.HasIndex(e => e.ID_CHAMADO, "NonClusteredIndex-20200414-145819");

                entity.Property(e => e.DATA_RESPOSTA).HasColumnType("datetime");

                entity.Property(e => e.MATRICULA_RESPONSAVEL).IsUnicode(false);

                entity.Property(e => e.RESPOSTA)
                    .IsRequired()
                    .IsUnicode(false);
            });

            modelBuilder.Entity<CONTROLE_DE_DEMANDAS_FILA>(entity =>
            {
                entity.ToTable("CONTROLE_DE_DEMANDAS_FILA");

                entity.Property(e => e.ADD_CAMPOS_AUTOMATICOS)
                    .HasMaxLength(3)
                    .IsUnicode(false);

                entity.Property(e => e.ADD_CAMPOS_MUNICIPIOS)
                    .HasMaxLength(3)
                    .IsUnicode(false);

                entity.Property(e => e.ADD_PDV_DESTINO)
                    .HasMaxLength(3)
                    .IsUnicode(false);

                entity.Property(e => e.FILA).IsUnicode(false);

                entity.Property(e => e.MAT_QUEM_CRIOU).IsUnicode(false);

                entity.Property(e => e.REGIONAL)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.TIPO_CHAMADO)
                    .HasMaxLength(550)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<CONTROLE_DE_DEMANDAS_OPERADORE>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("CONTROLE_DE_DEMANDAS_OPERADORES");

                entity.Property(e => e.LOGIN)
                    .IsRequired()
                    .IsUnicode(false);

                entity.Property(e => e.NIVEL)
                    .IsRequired()
                    .IsUnicode(false);

                entity.Property(e => e.NOME)
                    .IsRequired()
                    .IsUnicode(false);

                entity.Property(e => e.UF)
                    .HasMaxLength(10)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<CONTROLE_DE_DEMANDAS_RELACAO_CAMPOS_CHAMADO>(entity =>
            {
                entity.HasKey(e => e.ID)
                    .HasName("PK__CONTROLE__3214EC265180919D")
                    .IsClustered(false);

                entity.ToTable("CONTROLE_DE_DEMANDAS_RELACAO_CAMPOS_CHAMADO");

                entity.HasIndex(e => e.ID_CAMPOS_CHAMADO, "ClusteredIndex-20200414-144037")
                    .IsClustered();

                entity.Property(e => e.CAMPO)
                    .IsRequired()
                    .IsUnicode(false);

                entity.Property(e => e.VALOR)
                    .IsRequired()
                    .IsUnicode(false);
            });

            modelBuilder.Entity<CONTROLE_DE_DEMANDAS_RELACAO_CAMPOS_CHAMADO_BKP>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("CONTROLE_DE_DEMANDAS_RELACAO_CAMPOS_CHAMADO_BKP");

                entity.Property(e => e.CAMPO)
                    .IsRequired()
                    .IsUnicode(false);

                entity.Property(e => e.VALOR)
                    .IsRequired()
                    .IsUnicode(false);
            });

            modelBuilder.Entity<CONTROLE_DE_DEMANDAS_RELACAO_ITENS_CAMPO_COMBOBOX_FILA>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("CONTROLE_DE_DEMANDAS_RELACAO_ITENS_CAMPO_COMBOBOX_FILA");

                entity.Property(e => e.DESCRICAO)
                    .IsRequired()
                    .IsUnicode(false);

                entity.Property(e => e.ID).ValueGeneratedOnAdd();
            });

            modelBuilder.Entity<CONTROLE_DE_DEMANDAS_RELACAO_STATUS_CHAMADO>(entity =>
            {
                entity.ToTable("CONTROLE_DE_DEMANDAS_RELACAO_STATUS_CHAMADO");

                entity.Property(e => e.DATA).HasColumnType("datetime");

                entity.Property(e => e.ID_RESPOSTA).IsUnicode(false);

                entity.Property(e => e.MAT_QUEM_REDIRECIONOU).IsUnicode(false);

                entity.Property(e => e.STATUS)
                    .IsRequired()
                    .IsUnicode(false);
            });

            modelBuilder.Entity<CONTROLE_DE_DEMANDAS_RESPONSAVEL_FILA>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("CONTROLE_DE_DEMANDAS_RESPONSAVEL_FILA");

                entity.Property(e => e.MATRICULA_RESPONSAVEL).IsUnicode(false);
            });

            modelBuilder.Entity<CONTROLE_DE_DEMANDAS_STATUS_CHAMADO>(entity =>
            {
                entity.ToTable("CONTROLE_DE_DEMANDAS_STATUS_CHAMADO");
            });

            modelBuilder.Entity<CONTROLE_DE_DEMANDAS_SUGESTOES_NOMES_CAMPO>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("CONTROLE_DE_DEMANDAS_SUGESTOES_NOMES_CAMPOS");

                entity.Property(e => e.CAMPO).IsUnicode(false);

                entity.Property(e => e.MASCARA).IsUnicode(false);
            });

            modelBuilder.Entity<CREDENCIAMENTO_PROSPECT>(entity =>
            {
                entity.ToTable("CREDENCIAMENTO_PROSPECT");

                entity.Property(e => e.CANAL_CREDENCIAMENTO).IsUnicode(false);

                entity.Property(e => e.CIDADE).IsUnicode(false);

                entity.Property(e => e.DATA_ABERTURA).HasColumnType("datetime");

                entity.Property(e => e.DATA_PREVISTA_CREDENCIAMENTO)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.DATA_TORNOU_CREDENCIAMENTO).HasColumnType("datetime");

                entity.Property(e => e.DDD)
                    .HasMaxLength(2)
                    .IsUnicode(false);

                entity.Property(e => e.MATRICULA_SOLICITANTE).IsUnicode(false);

                entity.Property(e => e.OBSERVACAO).IsUnicode(false);

                entity.Property(e => e.RAZAO_SOCIAL).IsUnicode(false);

                entity.Property(e => e.REGIONAL).IsUnicode(false);

                entity.Property(e => e.TIPO_REVENDA).IsUnicode(false);

                entity.Property(e => e.UF)
                    .HasMaxLength(2)
                    .IsUnicode(false);

                entity.Property(e => e.data_ultimo_status).HasColumnType("datetime");

                entity.Property(e => e.ultimo_status)
                    .HasMaxLength(255)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Carteira_NE>(entity =>
            {
                entity.ToTable("Carteira_NE");

                entity.Property(e => e.ANOMES)
                    .HasMaxLength(128)
                    .IsUnicode(false);

                entity.Property(e => e.AREA_ATUAÇÃO_DDD)
                    .HasMaxLength(255)
                    .HasColumnName("AREA ATUAÇÃO DDD");

                entity.Property(e => e.Agencia)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.Area)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.Atividade).HasMaxLength(255);

                entity.Property(e => e.Bairro).HasMaxLength(255);

                entity.Property(e => e.Banco)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.Canal).HasMaxLength(255);

                entity.Property(e => e.Cep).HasMaxLength(255);

                entity.Property(e => e.Cidade).HasMaxLength(255);

                entity.Property(e => e.Cnpj).HasMaxLength(255);

                entity.Property(e => e.CodigoBanco)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.CodigoCliente)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.CodigoFornecedor)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.Complemento).HasMaxLength(255);

                entity.Property(e => e.Contato)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.DT_MOD_CAD)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.DataFimContrato)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.DataInicioContrato)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.Data_Credenciamento)
                    .HasMaxLength(255)
                    .HasColumnName("Data Credenciamento");

                entity.Property(e => e.Data_Descredenciamento)
                    .HasMaxLength(255)
                    .HasColumnName("Data Descredenciamento");

                entity.Property(e => e.DigitoVerificador)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.EmailComercial)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.EmailDivulgação)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.EmailFinanceiro)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.Endereco).HasMaxLength(255);

                entity.Property(e => e.Estrelagem).HasMaxLength(255);

                entity.Property(e => e.GA___GG)
                    .HasMaxLength(255)
                    .HasColumnName("GA / GG");

                entity.Property(e => e.GGP).HasMaxLength(255);

                entity.Property(e => e.GSS).HasMaxLength(255);

                entity.Property(e => e.GV).HasMaxLength(255);

                entity.Property(e => e.Genero)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.InscriçãoEstadual)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.Ixos)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.LOGIN_MOD_CAD)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.Local_Loja)
                    .HasMaxLength(255)
                    .HasColumnName("Local Loja");

                entity.Property(e => e.LoginSiebel).HasMaxLength(255);

                entity.Property(e => e.MT).HasMaxLength(255);

                entity.Property(e => e.Metragem).HasMaxLength(255);

                entity.Property(e => e.Modelo_Loja)
                    .HasMaxLength(255)
                    .HasColumnName("Modelo Loja");

                entity.Property(e => e.NO_GSS)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.NO_VIVO360)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.NO_VIVONEXT)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.NomeFantasia).HasMaxLength(255);

                entity.Property(e => e.Numero).HasMaxLength(255);

                entity.Property(e => e.NumeroConta)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.OptanteSimples)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.PontoVenda)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.Qt_de_PA)
                    .HasMaxLength(255)
                    .HasColumnName("Qt de PA");

                entity.Property(e => e.REDE).HasMaxLength(255);

                entity.Property(e => e.RE_GA).HasMaxLength(255);

                entity.Property(e => e.RE_GGP).HasMaxLength(255);

                entity.Property(e => e.RE_GV).HasMaxLength(255);

                entity.Property(e => e.RazaoSocial).HasMaxLength(255);

                entity.Property(e => e.SEGMENTAÇÃO).HasMaxLength(255);

                entity.Property(e => e.SetorAtividade)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.StatusCallidus).HasMaxLength(255);

                entity.Property(e => e.Telefone)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.Tipo_Loja)
                    .HasMaxLength(255)
                    .HasColumnName("Tipo Loja");

                entity.Property(e => e.Uf).HasMaxLength(255);

                entity.Property(e => e.Vendedor).HasMaxLength(255);
            });

            modelBuilder.Entity<FIXA_BASE_PRUMA>(entity =>
            {
                entity.ToTable("FIXA_BASE_PRUMA");

                entity.Property(e => e.ARMARIO)
                    .HasMaxLength(128)
                    .IsUnicode(false);

                entity.Property(e => e.ARMARIO_COBRE)
                    .HasMaxLength(128)
                    .IsUnicode(false);

                entity.Property(e => e.BAIRRO)
                    .HasMaxLength(128)
                    .IsUnicode(false);

                entity.Property(e => e.CAIXA)
                    .HasMaxLength(4000)
                    .IsUnicode(false);

                entity.Property(e => e.CEP_NUM)
                    .HasMaxLength(128)
                    .IsUnicode(false);

                entity.Property(e => e.CIDADE)
                    .HasMaxLength(128)
                    .IsUnicode(false);

                entity.Property(e => e.CLASSE)
                    .HasMaxLength(128)
                    .IsUnicode(false);

                entity.Property(e => e.COMPLEMENTO)
                    .HasMaxLength(128)
                    .IsUnicode(false);

                entity.Property(e => e.CONCORRENCIA)
                    .HasMaxLength(128)
                    .IsUnicode(false);

                entity.Property(e => e.DATA_ESTEIRA)
                    .HasMaxLength(26)
                    .IsUnicode(false);

                entity.Property(e => e.DAT_INSERCAO)
                    .HasMaxLength(26)
                    .IsUnicode(false);

                entity.Property(e => e.DAT_LIB_COMERCIAL)
                    .HasMaxLength(26)
                    .IsUnicode(false);

                entity.Property(e => e.ESTEIRA)
                    .HasMaxLength(128)
                    .IsUnicode(false);

                entity.Property(e => e.LOGRADOURO)
                    .HasMaxLength(128)
                    .IsUnicode(false);

                entity.Property(e => e.MOTIVO)
                    .HasMaxLength(128)
                    .IsUnicode(false);

                entity.Property(e => e.NOM_CONDOMINIO)
                    .HasMaxLength(128)
                    .IsUnicode(false);

                entity.Property(e => e.NOM_CONTOBRAEXT)
                    .HasMaxLength(128)
                    .IsUnicode(false);

                entity.Property(e => e.NOM_CONTVIST)
                    .HasMaxLength(128)
                    .IsUnicode(false);

                entity.Property(e => e.NOM_PREDIO)
                    .HasMaxLength(128)
                    .IsUnicode(false);

                entity.Property(e => e.PRIORIDADE)
                    .HasMaxLength(128)
                    .IsUnicode(false);

                entity.Property(e => e.PROSPECTOR)
                    .HasMaxLength(128)
                    .IsUnicode(false);

                entity.Property(e => e.REDE)
                    .HasMaxLength(128)
                    .IsUnicode(false);

                entity.Property(e => e.REGIONAL)
                    .HasMaxLength(26)
                    .IsUnicode(false);

                entity.Property(e => e.SEGMENTO)
                    .HasMaxLength(128)
                    .IsUnicode(false);

                entity.Property(e => e.STATUS)
                    .HasMaxLength(128)
                    .IsUnicode(false);

                entity.Property(e => e.TIPO)
                    .HasMaxLength(128)
                    .IsUnicode(false);

                entity.Property(e => e.UF)
                    .HasMaxLength(26)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<FIXA_VIEW_PAINEL_DE_ROTA>(entity =>
            {
                entity.ToTable("FIXA_VIEW_PAINEL_DE_ROTAS");

                entity.Property(e => e.AGING_ARMÁRIO)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.ARMÁRIO)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.BADDEBT)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.BAIRRO)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.BLOCOS)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.CAIXA)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.CAPACIDADE)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.CEP)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.CEP_NUM)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.CIDADE)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.CLASSE_A)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.CLASSE_AB)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.CLASSE_B)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.CLASSE_C)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.CLIENTE_FTTC)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.CLIENTE_FTTC_POR_DISPONIBILIDADE)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.COD_CONDOMINIO)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.DATA_ARMÁRIO)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.DATA_ESTEIRA)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.DDD)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.DISPONÍVEL)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.ESTEIRA)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.FRAUDE)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.LOGRADOURO)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.MICRORREGIÃO)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.MIGRAÇÃO)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NOM_CONDOMINIO)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.NÚMERO)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.OCUPAÇÃO)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.PRIORIDADE)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.QTD_APARTAMENTO)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.SEGMENTO)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.STATUS_LOTE)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TERRITÓRIO)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TIPO)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TIPO_RESIDENCIA)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TITULO)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.UF)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.USADOS)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.VENDAS)
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<HISTORICO_ACESSOS_MOBILE_PENDENTE>(entity =>
            {
                entity.ToTable("HISTORICO_ACESSOS_MOBILE_PENDENTE");

                entity.Property(e => e.DATA)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.MATRICULA)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.RESPOSTA)
                    .IsRequired()
                    .IsUnicode(false);

                entity.Property(e => e.STATUS)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<JORNADA_BD_ANSWER_ALTERNATIVA>(entity =>
            {
                entity.HasKey(e => e.ID_ALTERNATIVA)
                    .HasName("PK__JORNADA___6759B3ED9D446566");

                entity.ToTable("JORNADA_BD_ANSWER_ALTERNATIVAS");
            });

            modelBuilder.Entity<JORNADA_BD_ANSWER_AVALIACAO>(entity =>
            {
                entity.ToTable("JORNADA_BD_ANSWER_AVALIACAO");

                entity.Property(e => e.CADERNO).HasMaxLength(255);

                entity.Property(e => e.DDD_AVALIADO).IsUnicode(false);

                entity.Property(e => e.DT_AVALIACAO).HasMaxLength(255);

                entity.Property(e => e.MATRICULA_APLICADOR).HasMaxLength(255);

                entity.Property(e => e.NOME_APLICADOR).HasMaxLength(255);

                entity.Property(e => e.NOTA).HasMaxLength(255);

                entity.Property(e => e.PDV_AVALIADO).IsUnicode(false);

                entity.Property(e => e.PUBLICO_CANAL).HasMaxLength(255);

                entity.Property(e => e.PUBLICO_CARGO).HasMaxLength(255);

                entity.Property(e => e.REDE_AVALIADA).IsUnicode(false);

                entity.Property(e => e.RE_AVALIADO).IsUnicode(false);

                entity.Property(e => e.TEMA).IsUnicode(false);

                entity.Property(e => e.TP_FORMS).HasMaxLength(255);
            });

            modelBuilder.Entity<JORNADA_BD_AVALIACAO_RETORNO>(entity =>
            {
                entity.ToTable("JORNADA_BD_AVALIACAO_RETORNO");

                entity.Property(e => e.CADERNO).HasMaxLength(255);

                entity.Property(e => e.DDD_AVALIADO).IsUnicode(false);

                entity.Property(e => e.DT_AVALIACAO).HasMaxLength(255);

                entity.Property(e => e.ID_QUESTION).HasMaxLength(255);

                entity.Property(e => e.MATRICULA_APLICADOR).HasMaxLength(255);

                entity.Property(e => e.PDV_AVALIADO).IsUnicode(false);

                entity.Property(e => e.PESO).HasMaxLength(255);

                entity.Property(e => e.PUBLICO_CANAL).HasMaxLength(255);

                entity.Property(e => e.PUBLICO_CARGO).HasMaxLength(255);

                entity.Property(e => e.REDE_AVALIADA).IsUnicode(false);

                entity.Property(e => e.RESPOSTA_USER).IsUnicode(false);

                entity.Property(e => e.RE_AVALIADO).IsUnicode(false);

                entity.Property(e => e.TEMA).HasMaxLength(255);

                entity.Property(e => e.TP_FORMS).HasMaxLength(255);
            });

            modelBuilder.Entity<JORNADA_BD_CARGOS_CANAL>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("JORNADA_BD_CARGOS_CANAL");

                entity.Property(e => e.CANAL).HasMaxLength(255);

                entity.Property(e => e.CARGO).HasMaxLength(255);
            });

            modelBuilder.Entity<JORNADA_BD_QUESTION>(entity =>
            {
                entity.HasKey(e => e.ID_QUESTION)
                    .HasName("PK__JORNADA___331A4B0AD52DC391");

                entity.ToTable("JORNADA_BD_QUESTION");

                entity.Property(e => e.CANAL).HasMaxLength(255);

                entity.Property(e => e.CARGO).HasMaxLength(255);

                entity.Property(e => e.DT_MOD)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.LOGIN_MOD)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.PERGUNTA).IsUnicode(false);

                entity.Property(e => e.RESPOSTA_CORRETA).IsUnicode(false);

                entity.Property(e => e.SUB_TEMA)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.TEMA).HasMaxLength(255);

                entity.Property(e => e.TP_FORMS).HasMaxLength(255);

                entity.Property(e => e.TP_QUESTAO).HasMaxLength(255);
            });

            modelBuilder.Entity<JORNADA_BD_QUESTION_HISTORICO>(entity =>
            {
                entity.HasKey(e => e.ID_PROVA)
                    .HasName("PK__JORNADA___79F0FBF3E6AFD006");

                entity.ToTable("JORNADA_BD_QUESTION_HISTORICO");

                entity.Property(e => e.CANAL).HasMaxLength(255);

                entity.Property(e => e.CARGO).IsUnicode(false);

                entity.Property(e => e.DT_CRIACAO).HasMaxLength(255);

                entity.Property(e => e.DT_FINALIZACAO).IsUnicode(false);

                entity.Property(e => e.DT_INICIO_AVALIACAO).IsUnicode(false);

                entity.Property(e => e.FIXA).IsUnicode(false);

                entity.Property(e => e.ID_CRIADOR).HasMaxLength(255);

                entity.Property(e => e.TP_FORMS).IsUnicode(false);
            });

            modelBuilder.Entity<JORNADA_BD_TEMAS_SUB_TEMA>(entity =>
            {
                entity.HasKey(e => e.ID_SUB_TEMAS)
                    .HasName("PK__JORNADA___DE5581391EF734BB");

                entity.ToTable("JORNADA_BD_TEMAS_SUB_TEMAS");

                entity.Property(e => e.SUB_TEMAS)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.TEMAS)
                    .HasMaxLength(255)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<PERFIL_VIVO_TASK>(entity =>
            {
                entity.ToTable("PERFIL_VIVO_TASK");

                entity.Property(e => e.CARGO)
                    .HasMaxLength(255)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<SUB_FILA>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("SUB_FILA");

                entity.Property(e => e.DATA_CRIACAO).IsUnicode(false);

                entity.Property(e => e.ID_SUB_FILA).ValueGeneratedOnAdd();

                entity.Property(e => e.NOME_SUB_FILA)
                    .IsRequired()
                    .IsUnicode(false);

                entity.Property(e => e.REGIONAL)
                    .IsRequired()
                    .IsUnicode(false);
            });

            modelBuilder.Entity<TAB_PESSOAS_SUPORTE>(entity =>
            {
                entity.ToTable("TAB_PESSOAS_SUPORTE");

                entity.Property(e => e.CARGO).HasMaxLength(255);

                entity.Property(e => e.EMAIL).HasMaxLength(255);

                entity.Property(e => e.NAME).HasMaxLength(255);
            });

            modelBuilder.Entity<TIPO_FILA>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("TIPO_FILA");

                entity.Property(e => e.DT_CRIACAO)
                    .IsRequired()
                    .IsUnicode(false);

                entity.Property(e => e.ID).ValueGeneratedOnAdd();

                entity.Property(e => e.NOME_TIPO_FILA)
                    .IsRequired()
                    .IsUnicode(false);

                entity.Property(e => e.REGIONAL)
                    .IsRequired()
                    .IsUnicode(false);
            });

            modelBuilder.Entity<VALORES_CAMPOS_SUSPENSO>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("VALORES_CAMPOS_SUSPENSO");

                entity.Property(e => e.ID_VALORES).ValueGeneratedOnAdd();

                entity.Property(e => e.VALOR)
                    .IsRequired()
                    .IsUnicode(false);
            });

            modelBuilder.Entity<carteira_demais_canais_rede_colaborador>(entity =>
            {
                entity.HasKey(e => e.REDE)
                    .HasName("PK__carteira__45467F492278E84C");

                entity.ToTable("carteira_demais_canais_rede_colaborador");

                entity.Property(e => e.REDE).HasMaxLength(100);

                entity.Property(e => e.CANAL).HasMaxLength(30);

                entity.Property(e => e.MATRICULA_1)
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.MATRICULA_10)
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.MATRICULA_11)
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.MATRICULA_12)
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.MATRICULA_13)
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.MATRICULA_14)
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.MATRICULA_15)
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.MATRICULA_2)
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.MATRICULA_3)
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.MATRICULA_4)
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.MATRICULA_5)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.MATRICULA_6).HasMaxLength(10);

                entity.Property(e => e.MATRICULA_7).HasMaxLength(10);

                entity.Property(e => e.MATRICULA_8)
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.MATRICULA_9)
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.SAL)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.Uf).HasMaxLength(10);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}