// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shared_Static_Class.DB_Context_Vivo_MAIS;

#nullable disable

namespace Vivo_Apps_API.Migrations.ForumRTCZ
{
    [DbContext(typeof(ForumRTCZContext))]
    [Migration("20241014215313_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Latin1_General_CI_AS")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shared_Static_Class.Data.ACESSOS_MOBILE", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CANAL")
                        .HasColumnType("int");

                    b.Property<int>("CARGO")
                        .HasColumnType("int");

                    b.Property<string>("CPF")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int?>("DDD")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DT_MOD")
                        .HasColumnType("datetime");

                    b.Property<bool?>("ELEGIVEL")
                        .HasColumnType("bit");

                    b.Property<string>("EMAIL")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("FIXA")
                        .HasColumnType("bit");

                    b.Property<int?>("LOGIN_MOD")
                        .HasColumnType("int");

                    b.Property<int>("MATRICULA")
                        .HasColumnType("int");

                    b.Property<string>("NOME")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("OBS")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("PDV")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("REGIONAL")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("SENHA")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("STATUS")
                        .HasColumnType("bit");

                    b.Property<string>("TELEFONE")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TP_AFASTAMENTO")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("TP_STATUS")
                        .HasColumnType("int");

                    b.Property<string>("UF")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<byte[]>("UserAvatar")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("ID");

                    b.ToTable("ACESSOS_MOBILE", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Shared_Static_Class.Data.JORNADA_BD_TEMAS_SUB_TEMA", b =>
                {
                    b.Property<int>("ID_SUB_TEMAS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_SUB_TEMAS"));

                    b.Property<int?>("ID_TEMAS")
                        .HasColumnType("int");

                    b.Property<string>("SUB_TEMAS")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TEMAS")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ID_SUB_TEMAS");

                    b.ToTable("JORNADA_BD_TEMAS_SUB_TEMAS", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Shared_Static_Class.Data.PERFIL_USUARIO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("DT_MOD")
                        .HasColumnType("datetime");

                    b.Property<int?>("LOGIN_MOD")
                        .HasColumnType("int");

                    b.Property<int?>("MATRICULA")
                        .HasColumnType("int");

                    b.Property<int?>("id_Perfil")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("PERFIL_USUARIO", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Shared_Static_Class.Model_ForumRTCZ_Context.AVALIACAO_PUBLICACAO", b =>
                {
                    b.Property<Guid>("ID_AVALIACAO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AVALIACAO")
                        .HasColumnType("int");

                    b.Property<Guid>("ID_PUBLICACAO")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MATRICULA_RESPONSAVEL")
                        .HasColumnType("int");

                    b.HasKey("ID_AVALIACAO");

                    b.HasIndex("ID_PUBLICACAO");

                    b.HasIndex("MATRICULA_RESPONSAVEL");

                    b.ToTable("FORUM_AVALIACAO_PUBLICACAO", "Fórum");
                });

            modelBuilder.Entity("Shared_Static_Class.Model_ForumRTCZ_Context.PUBLICACAO_SOLICITACAO", b =>
                {
                    b.Property<Guid>("ID_SOLICITACAO_PUBLICACAO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("HORA")
                        .HasColumnType("datetime2");

                    b.Property<int>("MAT_RESPONSAVEL")
                        .HasColumnType("int");

                    b.Property<int>("SUB_TEMA")
                        .HasColumnType("int");

                    b.Property<string>("TEXT_PUBLICACAO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_SOLICITACAO_PUBLICACAO");

                    b.HasIndex("MAT_RESPONSAVEL");

                    b.HasIndex("SUB_TEMA");

                    b.ToTable("FORUM_PUBLICACAO_SOLICITACAO", "Fórum");
                });

            modelBuilder.Entity("Shared_Static_Class.Model_ForumRTCZ_Context.RESPONSAVEL_TEMA", b =>
                {
                    b.Property<Guid>("ID_RESPONSAVEL_TEMA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("HORA")
                        .HasColumnType("datetime2");

                    b.Property<int>("MATRICULA_RESPONSAVEL")
                        .HasColumnType("int");

                    b.Property<int>("SUB_TEMA")
                        .HasColumnType("int");

                    b.HasKey("ID_RESPONSAVEL_TEMA");

                    b.HasIndex("MATRICULA_RESPONSAVEL");

                    b.HasIndex("SUB_TEMA");

                    b.ToTable("FORUM_RESPONSAVEL_TEMA", "Fórum");
                });

            modelBuilder.Entity("Shared_Static_Class.Model_ForumRTCZ_Context.RESPOSTA_PUBLICACAO", b =>
                {
                    b.Property<Guid>("ID_PUBLICACAO")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("HORA")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ID_SOLICITACAO_PUBLICACAO")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MAT_SOLICITANTE")
                        .HasColumnType("int");

                    b.Property<int>("SUB_TEMA")
                        .HasColumnType("int");

                    b.Property<string>("TEXT_PUBLICACAO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_PUBLICACAO");

                    b.HasIndex("MAT_SOLICITANTE");

                    b.HasIndex("SUB_TEMA");

                    b.ToTable("FORUM_PUBLICACAO", "Fórum");
                });

            modelBuilder.Entity("Shared_Static_Class.Model_ForumRTCZ_Context.AVALIACAO_PUBLICACAO", b =>
                {
                    b.HasOne("Shared_Static_Class.Model_ForumRTCZ_Context.RESPOSTA_PUBLICACAO", "Resposta_Publicacao")
                        .WithMany("Avaliacao")
                        .HasForeignKey("ID_PUBLICACAO")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Shared_Static_Class.Model_ForumRTCZ_Context.PUBLICACAO_SOLICITACAO", "Publicacao_Principal")
                        .WithMany("Avaliacao")
                        .HasForeignKey("ID_PUBLICACAO")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Shared_Static_Class.Data.ACESSOS_MOBILE", "Responsavel")
                        .WithMany()
                        .HasForeignKey("MATRICULA_RESPONSAVEL")
                        .HasPrincipalKey("MATRICULA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacao_Principal");

                    b.Navigation("Responsavel");

                    b.Navigation("Resposta_Publicacao");
                });

            modelBuilder.Entity("Shared_Static_Class.Model_ForumRTCZ_Context.PUBLICACAO_SOLICITACAO", b =>
                {
                    b.HasOne("Shared_Static_Class.Data.ACESSOS_MOBILE", "Responsavel")
                        .WithMany()
                        .HasForeignKey("MAT_RESPONSAVEL")
                        .HasPrincipalKey("MATRICULA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared_Static_Class.Data.JORNADA_BD_TEMAS_SUB_TEMA", "Tema")
                        .WithMany()
                        .HasForeignKey("SUB_TEMA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Responsavel");

                    b.Navigation("Tema");
                });

            modelBuilder.Entity("Shared_Static_Class.Model_ForumRTCZ_Context.RESPONSAVEL_TEMA", b =>
                {
                    b.HasOne("Shared_Static_Class.Data.ACESSOS_MOBILE", "Responsavel")
                        .WithMany()
                        .HasForeignKey("MATRICULA_RESPONSAVEL")
                        .HasPrincipalKey("MATRICULA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared_Static_Class.Data.JORNADA_BD_TEMAS_SUB_TEMA", "Tema")
                        .WithMany()
                        .HasForeignKey("SUB_TEMA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Responsavel");

                    b.Navigation("Tema");
                });

            modelBuilder.Entity("Shared_Static_Class.Model_ForumRTCZ_Context.RESPOSTA_PUBLICACAO", b =>
                {
                    b.HasOne("Shared_Static_Class.Model_ForumRTCZ_Context.PUBLICACAO_SOLICITACAO", "Publicacao_alvo")
                        .WithMany("Respostas")
                        .HasForeignKey("ID_PUBLICACAO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared_Static_Class.Data.ACESSOS_MOBILE", "Solicitante")
                        .WithMany()
                        .HasForeignKey("MAT_SOLICITANTE")
                        .HasPrincipalKey("MATRICULA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared_Static_Class.Data.JORNADA_BD_TEMAS_SUB_TEMA", "Tema")
                        .WithMany()
                        .HasForeignKey("SUB_TEMA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacao_alvo");

                    b.Navigation("Solicitante");

                    b.Navigation("Tema");
                });

            modelBuilder.Entity("Shared_Static_Class.Model_ForumRTCZ_Context.PUBLICACAO_SOLICITACAO", b =>
                {
                    b.Navigation("Avaliacao");

                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("Shared_Static_Class.Model_ForumRTCZ_Context.RESPOSTA_PUBLICACAO", b =>
                {
                    b.Navigation("Avaliacao");
                });
#pragma warning restore 612, 618
        }
    }
}
