// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shared_Static_Class.DB_Context_Vivo_MAIS;

#nullable disable

namespace Vivo_Apps_API.Migrations.ForumRTCZ
{
    [DbContext(typeof(ForumRTCZContext))]
    [Migration("20241015132954_InsertDataTables")]
    partial class InsertDataTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Latin1_General_CI_AS")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shared_Static_Class.Data.ACESSOS_MOBILE", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CANAL")
                        .HasColumnType("int");

                    b.Property<int>("CARGO")
                        .HasColumnType("int");

                    b.Property<string>("CPF")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int?>("DDD")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DT_MOD")
                        .HasColumnType("datetime");

                    b.Property<bool?>("ELEGIVEL")
                        .HasColumnType("bit");

                    b.Property<string>("EMAIL")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("FIXA")
                        .HasColumnType("bit");

                    b.Property<int?>("LOGIN_MOD")
                        .HasColumnType("int");

                    b.Property<int>("MATRICULA")
                        .HasColumnType("int");

                    b.Property<string>("NOME")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("OBS")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("PDV")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("REGIONAL")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("SENHA")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("STATUS")
                        .HasColumnType("bit");

                    b.Property<string>("TELEFONE")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TP_AFASTAMENTO")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("TP_STATUS")
                        .HasColumnType("int");

                    b.Property<string>("UF")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<byte[]>("UserAvatar")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("ID");

                    b.ToTable("ACESSOS_MOBILE", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Shared_Static_Class.Data.JORNADA_BD_TEMAS_SUB_TEMA", b =>
                {
                    b.Property<int>("ID_SUB_TEMAS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_SUB_TEMAS"));

                    b.Property<int?>("ID_TEMAS")
                        .HasColumnType("int");

                    b.Property<string>("SUB_TEMAS")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TEMAS")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ID_SUB_TEMAS");

                    b.ToTable("JORNADA_BD_TEMAS_SUB_TEMAS", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Shared_Static_Class.Data.PERFIL_USUARIO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("DT_MOD")
                        .HasColumnType("datetime");

                    b.Property<int?>("LOGIN_MOD")
                        .HasColumnType("int");

                    b.Property<int?>("MATRICULA")
                        .HasColumnType("int");

                    b.Property<int?>("id_Perfil")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("PERFIL_USUARIO", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Shared_Static_Class.Model_ForumRTCZ_Context.AVALIACAO_PUBLICACAO", b =>
                {
                    b.Property<Guid>("ID_AVALIACAO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AVALIACAO")
                        .HasColumnType("int");

                    b.Property<Guid>("ID_PUBLICACAO")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MATRICULA_RESPONSAVEL")
                        .HasColumnType("int");

                    b.HasKey("ID_AVALIACAO");

                    b.HasIndex("ID_PUBLICACAO");

                    b.HasIndex("MATRICULA_RESPONSAVEL");

                    b.ToTable("FORUM_AVALIACAO_PUBLICACAO", "Fórum");
                });

            modelBuilder.Entity("Shared_Static_Class.Model_ForumRTCZ_Context.PUBLICACAO_SOLICITACAO", b =>
                {
                    b.Property<Guid>("ID_SOLICITACAO_PUBLICACAO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("HORA")
                        .HasColumnType("datetime2");

                    b.Property<int>("MAT_RESPONSAVEL")
                        .HasColumnType("int");

                    b.Property<int>("SUB_TEMA")
                        .HasColumnType("int");

                    b.Property<string>("TEXT_PUBLICACAO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_SOLICITACAO_PUBLICACAO");

                    b.HasIndex("MAT_RESPONSAVEL");

                    b.HasIndex("SUB_TEMA");

                    b.ToTable("FORUM_PUBLICACAO_SOLICITACAO", "Fórum");

                    b.HasData(
                        new
                        {
                            ID_SOLICITACAO_PUBLICACAO = new Guid("ce0a12e2-b5cc-4fa2-85ba-484f55829c07"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 712, DateTimeKind.Local).AddTicks(1229),
                            MAT_RESPONSAVEL = 80904800,
                            SUB_TEMA = 8,
                            TEXT_PUBLICACAO = "Apenas um teste de publicação no fórum do Giro V"
                        },
                        new
                        {
                            ID_SOLICITACAO_PUBLICACAO = new Guid("ad85237c-8d13-44a8-863e-e97ac07c9508"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 712, DateTimeKind.Local).AddTicks(1249),
                            MAT_RESPONSAVEL = 156114,
                            SUB_TEMA = 125,
                            TEXT_PUBLICACAO = "Apenas mais um teste de publicação no fórum do Giro V"
                        },
                        new
                        {
                            ID_SOLICITACAO_PUBLICACAO = new Guid("c3c9765e-c8cf-47e8-9444-604f76ff119a"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 712, DateTimeKind.Local).AddTicks(1250),
                            MAT_RESPONSAVEL = 3511507,
                            SUB_TEMA = 44,
                            TEXT_PUBLICACAO = "Apenas outro teste de publicação no fórum do Giro V"
                        });
                });

            modelBuilder.Entity("Shared_Static_Class.Model_ForumRTCZ_Context.RESPONSAVEL_TEMA", b =>
                {
                    b.Property<Guid>("ID_RESPONSAVEL_TEMA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("HORA")
                        .HasColumnType("datetime2");

                    b.Property<int>("MATRICULA_RESPONSAVEL")
                        .HasColumnType("int");

                    b.Property<int>("SUB_TEMA")
                        .HasColumnType("int");

                    b.HasKey("ID_RESPONSAVEL_TEMA");

                    b.HasIndex("MATRICULA_RESPONSAVEL");

                    b.HasIndex("SUB_TEMA");

                    b.ToTable("FORUM_RESPONSAVEL_TEMA", "Fórum");

                    b.HasData(
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("e42e7cbc-b48d-4749-8044-5dd551373e5a"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2016),
                            MATRICULA_RESPONSAVEL = 3511507,
                            SUB_TEMA = 78
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("cb76b829-e14d-4407-bece-9e72a656b271"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2062),
                            MATRICULA_RESPONSAVEL = 156727,
                            SUB_TEMA = 95
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("56ea8ddc-3374-4cc8-98a5-bcf3b8d8d6e7"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2070),
                            MATRICULA_RESPONSAVEL = 152001,
                            SUB_TEMA = 127
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("23b2f834-a6ca-464a-84cf-74249344e1cf"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2075),
                            MATRICULA_RESPONSAVEL = 64960,
                            SUB_TEMA = 94
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("f41270a7-4b9f-40a0-bef1-5c62bd0bda21"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2079),
                            MATRICULA_RESPONSAVEL = 157239,
                            SUB_TEMA = 32
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("3bcf13f7-9d0d-4004-af0a-05bd21907086"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2083),
                            MATRICULA_RESPONSAVEL = 3511507,
                            SUB_TEMA = 72
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("a4428460-083d-4518-b20f-6e0826853cbc"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2087),
                            MATRICULA_RESPONSAVEL = 51336,
                            SUB_TEMA = 48
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("344884b3-d3a9-4fb1-8e46-6da2cf4e2ed8"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2091),
                            MATRICULA_RESPONSAVEL = 47333,
                            SUB_TEMA = 50
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("4600a71b-db31-4d94-8782-9eaf0909679b"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2098),
                            MATRICULA_RESPONSAVEL = 40417113,
                            SUB_TEMA = 105
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("a53fcd15-020a-4aa8-adec-91eb5e6b7cc5"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2102),
                            MATRICULA_RESPONSAVEL = 3458749,
                            SUB_TEMA = 15
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("bb98fe78-ceaf-436e-b38d-516485985833"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2106),
                            MATRICULA_RESPONSAVEL = 40416900,
                            SUB_TEMA = 117
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("c7600ce5-4338-4ba9-b8f1-6f95721aedb8"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2110),
                            MATRICULA_RESPONSAVEL = 156305,
                            SUB_TEMA = 77
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("5e7474a7-fc47-4b34-babf-13dc28a7d8f3"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2114),
                            MATRICULA_RESPONSAVEL = 156114,
                            SUB_TEMA = 54
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("2c68e0b5-634a-40f5-8950-c3d041e9ed0f"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2118),
                            MATRICULA_RESPONSAVEL = 25183,
                            SUB_TEMA = 46
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("5b113012-baeb-4d7f-8d8c-dec584039b5a"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2122),
                            MATRICULA_RESPONSAVEL = 30722,
                            SUB_TEMA = 113
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("772d6c9d-f9ac-4431-96b1-c26db8659446"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2126),
                            MATRICULA_RESPONSAVEL = 156727,
                            SUB_TEMA = 46
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("1d4beae9-2c2c-4cf9-9b82-ee3684974f4f"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2132),
                            MATRICULA_RESPONSAVEL = 64960,
                            SUB_TEMA = 61
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("4fa9cd14-5038-4809-8225-2a5603149a2b"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2136),
                            MATRICULA_RESPONSAVEL = 69372,
                            SUB_TEMA = 29
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("34bccd68-7242-4b63-8ee3-3ad1ef1de304"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2140),
                            MATRICULA_RESPONSAVEL = 64960,
                            SUB_TEMA = 19
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("28ef2ff6-9a3f-432b-aa7b-30e0a57f7e0b"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2144),
                            MATRICULA_RESPONSAVEL = 64960,
                            SUB_TEMA = 122
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("08b97408-ddc8-47b3-a67e-a127a33fd49b"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2148),
                            MATRICULA_RESPONSAVEL = 51336,
                            SUB_TEMA = 113
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("57a536fe-3b11-4afb-905c-f0e00c54f221"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2152),
                            MATRICULA_RESPONSAVEL = 156114,
                            SUB_TEMA = 30
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("3015a19f-e037-45bf-82a6-8c89b2c39b9e"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2155),
                            MATRICULA_RESPONSAVEL = 80796597,
                            SUB_TEMA = 23
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("b4545e62-8a4b-4a5a-be35-4f0ee1a62f5c"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2159),
                            MATRICULA_RESPONSAVEL = 157239,
                            SUB_TEMA = 55
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("1945f3fc-bab8-4daa-aa29-c3e9c5cd9a35"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2206),
                            MATRICULA_RESPONSAVEL = 16279,
                            SUB_TEMA = 87
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("8810fa3c-7585-4bdd-9fe9-0fcf917d3781"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2210),
                            MATRICULA_RESPONSAVEL = 152001,
                            SUB_TEMA = 71
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("2727831e-ba61-4672-a3ab-7df07dbe04c4"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2214),
                            MATRICULA_RESPONSAVEL = 40418413,
                            SUB_TEMA = 110
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("a0d351a9-8622-4567-bdda-54b0eecaa9d9"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2218),
                            MATRICULA_RESPONSAVEL = 16279,
                            SUB_TEMA = 123
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("935bab5d-0429-450c-b571-f72580ce982d"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2223),
                            MATRICULA_RESPONSAVEL = 51336,
                            SUB_TEMA = 127
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("220f2dd5-89c8-4d4b-9df4-11026d87be16"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2226),
                            MATRICULA_RESPONSAVEL = 3511507,
                            SUB_TEMA = 102
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("7a0175bc-1f1e-47ab-a446-61dce5e87a5d"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2230),
                            MATRICULA_RESPONSAVEL = 80900909,
                            SUB_TEMA = 34
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("5a1aafc9-97d8-4afb-b2a4-5f68d031f2bc"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2234),
                            MATRICULA_RESPONSAVEL = 156114,
                            SUB_TEMA = 110
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("819d64cd-f2e7-4528-87a3-51edcb252848"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2241),
                            MATRICULA_RESPONSAVEL = 152001,
                            SUB_TEMA = 26
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("8215d2ef-8091-43d4-b6d8-0660d4f5156d"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2245),
                            MATRICULA_RESPONSAVEL = 157239,
                            SUB_TEMA = 67
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("2a589265-bd92-4c53-9bd4-717767f18ce9"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2249),
                            MATRICULA_RESPONSAVEL = 80886919,
                            SUB_TEMA = 118
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("be210a8f-c6f3-4d26-98ad-95695ed21c01"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2254),
                            MATRICULA_RESPONSAVEL = 40416900,
                            SUB_TEMA = 112
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("013a6820-7d4d-42b8-a276-f2d89856be7a"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2258),
                            MATRICULA_RESPONSAVEL = 25677,
                            SUB_TEMA = 72
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("266e2694-8d2f-4f94-ac64-e9d88473d009"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2261),
                            MATRICULA_RESPONSAVEL = 71114,
                            SUB_TEMA = 101
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("124aced3-39af-45a4-8879-6b9101f9a95c"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2265),
                            MATRICULA_RESPONSAVEL = 64960,
                            SUB_TEMA = 117
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("8f7b44f4-7046-43cf-ac7a-28ae7da408a7"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2269),
                            MATRICULA_RESPONSAVEL = 40416900,
                            SUB_TEMA = 10
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("cdc23935-c83f-44ce-bbe8-c2ecd09d7a61"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2275),
                            MATRICULA_RESPONSAVEL = 51336,
                            SUB_TEMA = 67
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("8fd2547a-6c31-4da9-bfc5-efaefe25e45f"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2279),
                            MATRICULA_RESPONSAVEL = 157239,
                            SUB_TEMA = 58
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("93d9ffb4-1ba7-4fd9-be1d-2596506e7a79"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2283),
                            MATRICULA_RESPONSAVEL = 80796597,
                            SUB_TEMA = 64
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("b23cad30-e32a-4dce-a4a2-6c307df9a313"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2286),
                            MATRICULA_RESPONSAVEL = 30722,
                            SUB_TEMA = 126
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("57e58807-53a7-446f-a91c-228fa6ed16e2"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2318),
                            MATRICULA_RESPONSAVEL = 80796597,
                            SUB_TEMA = 45
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("52374b74-ee7e-4765-b9a6-6b35af412c55"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2322),
                            MATRICULA_RESPONSAVEL = 3458749,
                            SUB_TEMA = 95
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("780a11a1-7590-4ae3-b8a1-cdf6764a54cd"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2326),
                            MATRICULA_RESPONSAVEL = 69372,
                            SUB_TEMA = 112
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("fc5c2929-8729-4c00-8054-e652ead777bf"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2330),
                            MATRICULA_RESPONSAVEL = 64960,
                            SUB_TEMA = 64
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("743eb16f-c5cf-4683-918c-25fe7df7f56c"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2336),
                            MATRICULA_RESPONSAVEL = 94842,
                            SUB_TEMA = 97
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("b9382c32-6280-4caf-a596-de2c0cda5862"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2340),
                            MATRICULA_RESPONSAVEL = 25183,
                            SUB_TEMA = 17
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("4f56d631-3521-4b1f-b563-597fa0e97e3e"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2345),
                            MATRICULA_RESPONSAVEL = 25677,
                            SUB_TEMA = 14
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("d25beb8f-5b58-42b5-9e77-8e698a91612f"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2349),
                            MATRICULA_RESPONSAVEL = 40416900,
                            SUB_TEMA = 128
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("8d45d58d-d73f-4824-b41e-9952d330295c"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2353),
                            MATRICULA_RESPONSAVEL = 69372,
                            SUB_TEMA = 43
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("00180491-a286-4e13-8853-4ef512c07c37"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2357),
                            MATRICULA_RESPONSAVEL = 47333,
                            SUB_TEMA = 120
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("8d55bd1c-db6a-4a8d-a519-3f2f94354615"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2361),
                            MATRICULA_RESPONSAVEL = 157239,
                            SUB_TEMA = 15
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("c83cd8ec-fac2-4df2-b784-6cf415b8221f"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2365),
                            MATRICULA_RESPONSAVEL = 157239,
                            SUB_TEMA = 121
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("a468c148-8f5a-439d-903d-758264b2c502"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2371),
                            MATRICULA_RESPONSAVEL = 94842,
                            SUB_TEMA = 88
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("37c70b81-8558-46dc-8d1f-e1012387db1b"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2374),
                            MATRICULA_RESPONSAVEL = 71114,
                            SUB_TEMA = 87
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("c119fd5a-0f6a-4fe1-8b20-ae9887aa71a5"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2408),
                            MATRICULA_RESPONSAVEL = 16279,
                            SUB_TEMA = 116
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("15bdffaa-5c77-4b64-8091-a51cbc788077"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2412),
                            MATRICULA_RESPONSAVEL = 3458749,
                            SUB_TEMA = 124
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("ba62de01-5852-4a44-95a2-c3ebc1da74aa"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2415),
                            MATRICULA_RESPONSAVEL = 152001,
                            SUB_TEMA = 76
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("09f11f6b-4e0a-4708-b344-7deee7d0c7a6"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2419),
                            MATRICULA_RESPONSAVEL = 40417113,
                            SUB_TEMA = 9
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("684c0e32-02ce-4c9d-a477-640df0de116d"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2423),
                            MATRICULA_RESPONSAVEL = 51336,
                            SUB_TEMA = 16
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("967030a6-ae5e-4d1f-8d93-79608c34bfc1"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2427),
                            MATRICULA_RESPONSAVEL = 152001,
                            SUB_TEMA = 62
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("3bd91fba-352c-4017-928d-9cee0da87363"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2433),
                            MATRICULA_RESPONSAVEL = 64960,
                            SUB_TEMA = 49
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("22b5f9f3-ed51-41b2-9f74-7261e1c10183"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2437),
                            MATRICULA_RESPONSAVEL = 94842,
                            SUB_TEMA = 96
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("da15c51b-6174-4e0d-8ccb-95d1294a8432"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2441),
                            MATRICULA_RESPONSAVEL = 80900909,
                            SUB_TEMA = 115
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("e7eb97e1-b360-42a5-9f1a-f13d02072913"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2445),
                            MATRICULA_RESPONSAVEL = 64960,
                            SUB_TEMA = 48
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("b9499cd5-d578-4dc0-9fa5-9a30b1ab5f77"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2449),
                            MATRICULA_RESPONSAVEL = 80886919,
                            SUB_TEMA = 73
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("e270f07a-c3b1-4f49-bce9-6604135e8e15"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2453),
                            MATRICULA_RESPONSAVEL = 80900909,
                            SUB_TEMA = 50
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("c6f3d1e9-51b2-41b6-bd94-baeeeba8c081"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2457),
                            MATRICULA_RESPONSAVEL = 47333,
                            SUB_TEMA = 106
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("2511e2f4-f38c-45b2-ac3c-9920c1b7ed2d"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2486),
                            MATRICULA_RESPONSAVEL = 64960,
                            SUB_TEMA = 99
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("2cbe8d4e-ae1d-4549-aed1-0895169d3706"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2494),
                            MATRICULA_RESPONSAVEL = 40416900,
                            SUB_TEMA = 69
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("7f87606b-b6f1-40d0-bb0f-d315af64f85a"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2498),
                            MATRICULA_RESPONSAVEL = 163794,
                            SUB_TEMA = 127
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("0556b6d9-9570-4889-b8c9-43b046cd2f36"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2502),
                            MATRICULA_RESPONSAVEL = 80904800,
                            SUB_TEMA = 67
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("0dbd64bf-c1c3-4c3c-afca-a7aebabfaf7b"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2505),
                            MATRICULA_RESPONSAVEL = 159706,
                            SUB_TEMA = 71
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("b35e775c-c5c7-43ee-ad37-dcd3905f1fc0"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2509),
                            MATRICULA_RESPONSAVEL = 30722,
                            SUB_TEMA = 10
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("6806c5de-7704-4c94-8bee-9a0b780ce10c"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2514),
                            MATRICULA_RESPONSAVEL = 3458749,
                            SUB_TEMA = 18
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("608ccaf5-38bb-40e5-9b02-f759663b45a0"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2518),
                            MATRICULA_RESPONSAVEL = 25677,
                            SUB_TEMA = 111
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("7123ced9-5fa4-4151-915f-ac730de016d7"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2522),
                            MATRICULA_RESPONSAVEL = 163794,
                            SUB_TEMA = 37
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("b3270037-b154-464a-ac56-00b649165b34"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2528),
                            MATRICULA_RESPONSAVEL = 30722,
                            SUB_TEMA = 109
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("1272ec7e-6c83-438e-b2de-f46708cd42c1"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2558),
                            MATRICULA_RESPONSAVEL = 40417113,
                            SUB_TEMA = 111
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("e153c75f-2d28-4586-84af-74d10d7b2d2c"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2562),
                            MATRICULA_RESPONSAVEL = 156114,
                            SUB_TEMA = 8
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("e4cac47f-28b6-4fb3-9e3d-d1df4c00c9bd"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2566),
                            MATRICULA_RESPONSAVEL = 69372,
                            SUB_TEMA = 55
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("d64a54df-4dc0-43e8-921f-7d55dd8a9be7"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2571),
                            MATRICULA_RESPONSAVEL = 40416900,
                            SUB_TEMA = 20
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("e314d157-1a24-4920-b3a8-e2ebd79c9447"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2575),
                            MATRICULA_RESPONSAVEL = 25677,
                            SUB_TEMA = 22
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("4819c4f0-70f9-4b0e-bc46-be1d195dae8a"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2578),
                            MATRICULA_RESPONSAVEL = 156727,
                            SUB_TEMA = 26
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("65b6be5b-30ee-47f0-9c37-a5d66381fb77"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2582),
                            MATRICULA_RESPONSAVEL = 163794,
                            SUB_TEMA = 68
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("dd15b101-116a-464f-80a6-613479c4385d"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2588),
                            MATRICULA_RESPONSAVEL = 51336,
                            SUB_TEMA = 128
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("0df30b0c-54b1-4766-91d5-2c914984ce52"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2592),
                            MATRICULA_RESPONSAVEL = 156114,
                            SUB_TEMA = 87
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("43bb999f-ece6-43f6-8022-242b70d229a6"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2597),
                            MATRICULA_RESPONSAVEL = 160624,
                            SUB_TEMA = 69
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("bb2931fd-97c1-4aaf-a6e2-80c275030241"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2630),
                            MATRICULA_RESPONSAVEL = 163794,
                            SUB_TEMA = 42
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("74ee64ca-37e0-4264-8d17-6d23d872395b"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2634),
                            MATRICULA_RESPONSAVEL = 156305,
                            SUB_TEMA = 112
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("6faff85c-efad-4160-b5fb-c0a269f841f5"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2638),
                            MATRICULA_RESPONSAVEL = 160624,
                            SUB_TEMA = 45
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("c0f15912-6a1b-488b-bda3-b2b4b3885c7d"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2642),
                            MATRICULA_RESPONSAVEL = 51336,
                            SUB_TEMA = 63
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("c63edf75-a9a4-4f55-819e-60fe76436f2d"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2646),
                            MATRICULA_RESPONSAVEL = 25677,
                            SUB_TEMA = 90
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("932a0433-9823-4156-b5af-d37a2cc5a283"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2653),
                            MATRICULA_RESPONSAVEL = 156305,
                            SUB_TEMA = 126
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("bf1d8d37-590d-4a97-b68f-f78e7505efff"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2657),
                            MATRICULA_RESPONSAVEL = 80886919,
                            SUB_TEMA = 57
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("a1c39d81-a20f-44dc-85a3-b2e9a70537ee"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2661),
                            MATRICULA_RESPONSAVEL = 51336,
                            SUB_TEMA = 68
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("f3e1a7e7-77cf-428b-afeb-3cbca965ad16"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2665),
                            MATRICULA_RESPONSAVEL = 80900909,
                            SUB_TEMA = 100
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("3144d93d-09aa-4a42-8d7e-1981ae2edd3d"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2686),
                            MATRICULA_RESPONSAVEL = 80904800,
                            SUB_TEMA = 83
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("5abb5921-a928-4a37-b2bb-f09a8c01f0a0"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2690),
                            MATRICULA_RESPONSAVEL = 80904800,
                            SUB_TEMA = 75
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("0125dbc1-2fc8-4e10-9707-b25bea8a22f8"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2695),
                            MATRICULA_RESPONSAVEL = 3511507,
                            SUB_TEMA = 17
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("025a9a99-fe05-4a03-941c-96de2cb71b19"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2699),
                            MATRICULA_RESPONSAVEL = 30722,
                            SUB_TEMA = 86
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("1798bf02-1daa-43af-acae-f15220b809f5"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2706),
                            MATRICULA_RESPONSAVEL = 80886919,
                            SUB_TEMA = 122
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("0909293a-bbdc-456f-bc30-a48f27786b62"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2710),
                            MATRICULA_RESPONSAVEL = 80900909,
                            SUB_TEMA = 75
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("5210b97f-7cda-4d2f-b529-813ab9953ec4"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2714),
                            MATRICULA_RESPONSAVEL = 156305,
                            SUB_TEMA = 105
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("2daec607-7fce-48be-89e1-bf79209a07fe"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2718),
                            MATRICULA_RESPONSAVEL = 40416900,
                            SUB_TEMA = 41
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("b4ef76e0-9015-478e-86bd-a84913c19695"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2760),
                            MATRICULA_RESPONSAVEL = 40417113,
                            SUB_TEMA = 127
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("d50a71be-41eb-49b5-85b0-27fe19d3765c"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2764),
                            MATRICULA_RESPONSAVEL = 47333,
                            SUB_TEMA = 31
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("35e6ad04-c3a8-400e-92d8-a44e213ac26a"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2768),
                            MATRICULA_RESPONSAVEL = 156114,
                            SUB_TEMA = 119
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("7b19c273-607d-4642-9843-05c2aed3905e"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2772),
                            MATRICULA_RESPONSAVEL = 160624,
                            SUB_TEMA = 61
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("62637e8f-802e-4747-92dc-c4939d9e168c"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2779),
                            MATRICULA_RESPONSAVEL = 80900909,
                            SUB_TEMA = 96
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("e5d7a4f8-afea-4b26-a576-14a3cf9cc09f"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2783),
                            MATRICULA_RESPONSAVEL = 163794,
                            SUB_TEMA = 99
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("93ee5549-b32f-47c7-ad60-16925d28de3d"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2787),
                            MATRICULA_RESPONSAVEL = 163794,
                            SUB_TEMA = 13
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("f82ec6c3-de2b-4331-b355-2f2c696071f9"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2791),
                            MATRICULA_RESPONSAVEL = 40416900,
                            SUB_TEMA = 34
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("6d24c9a8-543d-4957-9ae1-eeb474b68cb1"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2830),
                            MATRICULA_RESPONSAVEL = 156305,
                            SUB_TEMA = 82
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("81e4fc76-9113-4db2-8323-389cf933805e"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2834),
                            MATRICULA_RESPONSAVEL = 160624,
                            SUB_TEMA = 118
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("92e13575-24b0-49bd-9d75-626de0e73f89"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2838),
                            MATRICULA_RESPONSAVEL = 156727,
                            SUB_TEMA = 50
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("f0a6107d-3657-4d0d-841a-f8ec6f2bd478"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2842),
                            MATRICULA_RESPONSAVEL = 16279,
                            SUB_TEMA = 38
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("ad616b26-67f4-42d5-a485-de6d38daddb7"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2848),
                            MATRICULA_RESPONSAVEL = 25183,
                            SUB_TEMA = 19
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("c6890e30-06dd-4ef9-ab22-36cc996b0db7"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2852),
                            MATRICULA_RESPONSAVEL = 40417113,
                            SUB_TEMA = 69
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("71bc5ca4-492e-4f31-bf25-50e51472fdfb"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2856),
                            MATRICULA_RESPONSAVEL = 40416900,
                            SUB_TEMA = 19
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("425808ce-f2d3-466b-806c-27723ea4f4f6"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2886),
                            MATRICULA_RESPONSAVEL = 71114,
                            SUB_TEMA = 44
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("e2aac940-9abc-43b0-a342-9d65b820f2cd"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2890),
                            MATRICULA_RESPONSAVEL = 156727,
                            SUB_TEMA = 69
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("e59bba40-3081-4463-bd75-0d106d1d5f16"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2894),
                            MATRICULA_RESPONSAVEL = 152001,
                            SUB_TEMA = 61
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("30fed233-84d2-412d-b5c4-e21e307bb2f3"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2898),
                            MATRICULA_RESPONSAVEL = 159706,
                            SUB_TEMA = 98
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("f32e7ded-4d80-4df8-a3cc-48280cf9d5fb"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2902),
                            MATRICULA_RESPONSAVEL = 30722,
                            SUB_TEMA = 46
                        },
                        new
                        {
                            ID_RESPONSAVEL_TEMA = new Guid("6597e170-caf6-4e75-a2bf-eb479617d631"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 716, DateTimeKind.Local).AddTicks(2908),
                            MATRICULA_RESPONSAVEL = 71114,
                            SUB_TEMA = 29
                        });
                });

            modelBuilder.Entity("Shared_Static_Class.Model_ForumRTCZ_Context.RESPOSTA_PUBLICACAO", b =>
                {
                    b.Property<Guid>("ID_PUBLICACAO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("HORA")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ID_SOLICITACAO_PUBLICACAO")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MAT_SOLICITANTE")
                        .HasColumnType("int");

                    b.Property<string>("TEXT_PUBLICACAO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_PUBLICACAO");

                    b.HasIndex("ID_SOLICITACAO_PUBLICACAO");

                    b.HasIndex("MAT_SOLICITANTE");

                    b.ToTable("FORUM_PUBLICACAO", "Fórum");

                    b.HasData(
                        new
                        {
                            ID_PUBLICACAO = new Guid("b3b315d5-8b6c-4c2d-937b-2734856f92b6"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 717, DateTimeKind.Local).AddTicks(3616),
                            ID_SOLICITACAO_PUBLICACAO = new Guid("ce0a12e2-b5cc-4fa2-85ba-484f55829c07"),
                            MAT_SOLICITANTE = 160624,
                            TEXT_PUBLICACAO = "Sua pergunta faz total sentido, você vai tirar nota MIL! na prova do GiroV CONGRATULATIONS 👌🎉🎉"
                        },
                        new
                        {
                            ID_PUBLICACAO = new Guid("51b3f383-98a6-4118-985b-7cb56c800ad9"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 717, DateTimeKind.Local).AddTicks(3630),
                            ID_SOLICITACAO_PUBLICACAO = new Guid("ce0a12e2-b5cc-4fa2-85ba-484f55829c07"),
                            MAT_SOLICITANTE = 40417113,
                            TEXT_PUBLICACAO = "Sua pergunta faz total sentido, você vai tirar nota MIL! na prova do GiroV CONGRATULATIONS 👌🎉🎉"
                        },
                        new
                        {
                            ID_PUBLICACAO = new Guid("2677fd8a-201e-460b-8e10-3e8c9c01489c"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 717, DateTimeKind.Local).AddTicks(3632),
                            ID_SOLICITACAO_PUBLICACAO = new Guid("ce0a12e2-b5cc-4fa2-85ba-484f55829c07"),
                            MAT_SOLICITANTE = 40417113,
                            TEXT_PUBLICACAO = "Sua pergunta faz total sentido, você vai tirar nota MIL! na prova do GiroV CONGRATULATIONS 👌🎉🎉"
                        },
                        new
                        {
                            ID_PUBLICACAO = new Guid("70792ee4-0b63-4c06-a86c-4ed463c1d23e"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 717, DateTimeKind.Local).AddTicks(3634),
                            ID_SOLICITACAO_PUBLICACAO = new Guid("ad85237c-8d13-44a8-863e-e97ac07c9508"),
                            MAT_SOLICITANTE = 47333,
                            TEXT_PUBLICACAO = "Sua pergunta faz total sentido, você vai tirar nota MIL! na prova do GiroV CONGRATULATIONS 👌🎉🎉"
                        },
                        new
                        {
                            ID_PUBLICACAO = new Guid("7f43a799-b7a1-49cf-a34c-9b8f5e8747d3"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 717, DateTimeKind.Local).AddTicks(3636),
                            ID_SOLICITACAO_PUBLICACAO = new Guid("ad85237c-8d13-44a8-863e-e97ac07c9508"),
                            MAT_SOLICITANTE = 16279,
                            TEXT_PUBLICACAO = "Sua pergunta faz total sentido, você vai tirar nota MIL! na prova do GiroV CONGRATULATIONS 👌🎉🎉"
                        },
                        new
                        {
                            ID_PUBLICACAO = new Guid("723955eb-bf37-4232-b056-4b3bc2a50ed9"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 717, DateTimeKind.Local).AddTicks(3641),
                            ID_SOLICITACAO_PUBLICACAO = new Guid("ad85237c-8d13-44a8-863e-e97ac07c9508"),
                            MAT_SOLICITANTE = 80904800,
                            TEXT_PUBLICACAO = "Sua pergunta faz total sentido, você vai tirar nota MIL! na prova do GiroV CONGRATULATIONS 👌🎉🎉"
                        },
                        new
                        {
                            ID_PUBLICACAO = new Guid("a1657024-7d5e-4ca9-a7c5-f661241ef8bf"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 717, DateTimeKind.Local).AddTicks(3643),
                            ID_SOLICITACAO_PUBLICACAO = new Guid("c3c9765e-c8cf-47e8-9444-604f76ff119a"),
                            MAT_SOLICITANTE = 40416900,
                            TEXT_PUBLICACAO = "Sua pergunta faz total sentido, você vai tirar nota MIL! na prova do GiroV CONGRATULATIONS 👌🎉🎉"
                        },
                        new
                        {
                            ID_PUBLICACAO = new Guid("9288fcb6-fe87-4e8a-b46a-168a38cda267"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 717, DateTimeKind.Local).AddTicks(3651),
                            ID_SOLICITACAO_PUBLICACAO = new Guid("c3c9765e-c8cf-47e8-9444-604f76ff119a"),
                            MAT_SOLICITANTE = 80886919,
                            TEXT_PUBLICACAO = "Sua pergunta faz total sentido, você vai tirar nota MIL! na prova do GiroV CONGRATULATIONS 👌🎉🎉"
                        },
                        new
                        {
                            ID_PUBLICACAO = new Guid("c1fa5f30-348d-4296-a73b-d5927c900371"),
                            HORA = new DateTime(2024, 10, 15, 10, 29, 52, 717, DateTimeKind.Local).AddTicks(3653),
                            ID_SOLICITACAO_PUBLICACAO = new Guid("c3c9765e-c8cf-47e8-9444-604f76ff119a"),
                            MAT_SOLICITANTE = 25183,
                            TEXT_PUBLICACAO = "Sua pergunta faz total sentido, você vai tirar nota MIL! na prova do GiroV CONGRATULATIONS 👌🎉🎉"
                        });
                });

            modelBuilder.Entity("Shared_Static_Class.Model_ForumRTCZ_Context.AVALIACAO_PUBLICACAO", b =>
                {
                    b.HasOne("Shared_Static_Class.Model_ForumRTCZ_Context.RESPOSTA_PUBLICACAO", "Resposta_Publicacao")
                        .WithMany("Avaliacao")
                        .HasForeignKey("ID_PUBLICACAO")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Shared_Static_Class.Model_ForumRTCZ_Context.PUBLICACAO_SOLICITACAO", "Publicacao_Principal")
                        .WithMany("Avaliacao")
                        .HasForeignKey("ID_PUBLICACAO")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Shared_Static_Class.Data.ACESSOS_MOBILE", "Responsavel")
                        .WithMany()
                        .HasForeignKey("MATRICULA_RESPONSAVEL")
                        .HasPrincipalKey("MATRICULA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacao_Principal");

                    b.Navigation("Responsavel");

                    b.Navigation("Resposta_Publicacao");
                });

            modelBuilder.Entity("Shared_Static_Class.Model_ForumRTCZ_Context.PUBLICACAO_SOLICITACAO", b =>
                {
                    b.HasOne("Shared_Static_Class.Data.ACESSOS_MOBILE", "Responsavel")
                        .WithMany()
                        .HasForeignKey("MAT_RESPONSAVEL")
                        .HasPrincipalKey("MATRICULA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared_Static_Class.Data.JORNADA_BD_TEMAS_SUB_TEMA", "Tema")
                        .WithMany()
                        .HasForeignKey("SUB_TEMA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Responsavel");

                    b.Navigation("Tema");
                });

            modelBuilder.Entity("Shared_Static_Class.Model_ForumRTCZ_Context.RESPONSAVEL_TEMA", b =>
                {
                    b.HasOne("Shared_Static_Class.Data.ACESSOS_MOBILE", "Responsavel")
                        .WithMany()
                        .HasForeignKey("MATRICULA_RESPONSAVEL")
                        .HasPrincipalKey("MATRICULA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared_Static_Class.Data.JORNADA_BD_TEMAS_SUB_TEMA", "Tema")
                        .WithMany()
                        .HasForeignKey("SUB_TEMA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Responsavel");

                    b.Navigation("Tema");
                });

            modelBuilder.Entity("Shared_Static_Class.Model_ForumRTCZ_Context.RESPOSTA_PUBLICACAO", b =>
                {
                    b.HasOne("Shared_Static_Class.Model_ForumRTCZ_Context.PUBLICACAO_SOLICITACAO", "Publicacao_alvo")
                        .WithMany("Respostas")
                        .HasForeignKey("ID_SOLICITACAO_PUBLICACAO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared_Static_Class.Data.ACESSOS_MOBILE", "Solicitante")
                        .WithMany()
                        .HasForeignKey("MAT_SOLICITANTE")
                        .HasPrincipalKey("MATRICULA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacao_alvo");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("Shared_Static_Class.Model_ForumRTCZ_Context.PUBLICACAO_SOLICITACAO", b =>
                {
                    b.Navigation("Avaliacao");

                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("Shared_Static_Class.Model_ForumRTCZ_Context.RESPOSTA_PUBLICACAO", b =>
                {
                    b.Navigation("Avaliacao");
                });
#pragma warning restore 612, 618
        }
    }
}
